import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {createPreviewApp} from '../apps/api/preview-server.mjs';
import {trackingCategories} from '../packages/domain/tracking.mjs';

const offline={configured:()=>false,run(){throw new Error('External research forbidden in this test.');}};
async function harness(research=offline){
  const root=mkdtempSync(join(tmpdir(),'pc-single-'));let app,base,cookie,csrf;
  async function open(){app=createPreviewApp({dataDir:root,assetsDir:join(root,'no-assets'),preview:{research},photoFlow:{research:offline,maps:{lookup:async()=>({mapped:null})}}});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+app.server.address().port;const res=await fetch(base+'/api/session');cookie=res.headers.get('set-cookie').split(';')[0];csrf=(await res.json()).csrf;}
  await open();const call=async(path,method='GET',body,headers={})=>{const r=await fetch(base+path,{method,headers:{cookie,Origin:base,'X-CSRF-Token':csrf,'Content-Type':'application/json',...headers},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};};
  return {call,get app(){return app;},get base(){return base;},start:extra=>call('/api/workspace/start','POST',{postcode:'RH2 9QQ',allowProcessing:true,requestKey:randomUUID(),...extra}),restart:async()=>{await app.close();await open();},close:async()=>{await app.close();rmSync(root,{recursive:true,force:true});}};
}
const rec=(extra={})=>({category:'water',title:'Investigate reported leak',place:'Ground floor',owner:'Example contractor',dueDate:'2030-01-01',description:'User-entered observation, not detected from the model.',requestKey:randomUUID(),...extra});
const path=bid=>'/api/workspace/buildings/'+bid;

test('postcode alone creates a labelled estimate and twelve empty tracking choices',async()=>{const f=await harness();try{const r=await f.start();assert.equal(r.status,200);assert.equal(r.data.building.name,'Building at RH2 9QQ');assert.ok(r.data.preview.spec.blocks.length);assert.equal(r.data.categories.length,12);assert.ok(r.data.categories.every(c=>!c.enabled&&c.count===0));assert.equal(r.data.records.length,0);assert.equal(f.app.workspace.locations(r.data.building.id).length,0);assert.match(r.data.notice,/not live monitoring/);}finally{await f.close();}});
test('postcode endpoint requires session, CSRF and deliberate creation consent',async()=>{const f=await harness();try{assert.equal((await fetch(f.base+'/api/workspace/buildings')).status,401);assert.equal((await f.start({allowProcessing:false})).status,400);assert.equal((await f.call('/api/workspace/start','POST',{postcode:'RH2 9QQ',requestKey:randomUUID(),allowProcessing:true},{'X-CSRF-Token':''})).status,403);}finally{await f.close();}});
test('invalid postcode and optional name do not create records',async()=>{const f=await harness();try{assert.equal((await f.start({postcode:'X'})).status,400);assert.equal((await f.start({name:'x'.repeat(151)})).status,400);assert.equal(f.app.workspace.buildings().length,0);}finally{await f.close();}});
test('normalised postcode reopens its only existing named building without new AI',async()=>{let calls=0;const f=await harness({configured:()=>true,run:async({spec})=>{calls++;return {spec,references:[],photos:[],basis:'ai-estimated',message:'Synthetic completed'};}});try{const a=await f.start({name:'Synthetic Court'});await new Promise(r=>setTimeout(r,20));const b=await f.start({postcode:'rh29qq'});assert.equal(b.data.building.id,a.data.building.id);assert.equal(calls,1);assert.equal(b.data.building.name,'Synthetic Court');}finally{await f.close();}});
test('repeated start keys recover lost responses without repeated processing',async()=>{const f=await harness();try{const key=randomUUID(),a=await f.start({requestKey:key}),b=await f.start({requestKey:key});assert.equal(a.data.preview.id,b.data.preview.id);assert.equal(b.data.duplicate,true);const recover=await f.call('/api/workspace/requests/'+key);assert.equal(recover.data.building.id,a.data.building.id);assert.equal((await f.start({requestKey:key,postcode:'RH1 1RT'})).status,409);}finally{await f.close();}});
test('several existing buildings at one postcode are offered inline rather than silently mixed',async()=>{const f=await harness();try{const a=await f.start({name:'Block A'});await f.start({name:'Block B'});const r=await f.start();assert.equal(r.data.kind,'choose');assert.equal(r.data.choices.length,2);const s=await f.start({buildingId:a.data.building.id});assert.equal(s.data.building.name,'Block A');assert.equal((await f.start({postcode:'RH1 1RT',buildingId:a.data.building.id})).status,400);}finally{await f.close();}});
test('category toggle is versioned and never invents assets or monitoring',async()=>{const f=await harness();try{const b=(await f.start()).data.building.id,u=path(b)+'/modules/fire-doors';const r=await f.call(u,'PUT',{version:0,enabled:true});assert.equal(r.status,200);assert.equal(r.data.summary.enabled,1);assert.equal(r.data.summary.records,0);assert.equal((await f.call(u,'PUT',{version:0,enabled:false})).status,409);assert.equal((await f.call(path(b)+'/modules/unknown','PUT',{version:0,enabled:true})).status,400);}finally{await f.close();}});
test('saving a tracking record persists an actual existing-workspace task and due date',async()=>{const f=await harness();try{const b=(await f.start()).data.building.id;const r=await f.call(path(b)+'/records','POST',rec());assert.equal(r.status,201);assert.equal(r.data.records[0].place,'Ground floor');assert.equal(r.data.records[0].owner,'Example contractor');assert.equal(r.data.records[0].due_date,'2030-01-01');assert.equal(f.app.workspace.tasks(b).length,1);assert.equal(r.data.categories.find(c=>c.id==='water').enabled,true);assert.equal(r.data.summary.open,1);}finally{await f.close();}});
test('tracking submission is idempotent after lost response and rejects changed retry payload',async()=>{const f=await harness();try{const b=(await f.start()).data.building.id,payload=rec();await f.call(path(b)+'/records','POST',payload);const r=await f.call(path(b)+'/records','POST',payload);assert.equal(r.data.records.length,1);assert.equal((await f.call(path(b)+'/records','POST',{...payload,title:'A changed request'})).status,409);}finally{await f.close();}});
test('impossible dates and oversized notes cannot create a partial task',async()=>{const f=await harness();try{const b=(await f.start()).data.building.id;for(const extra of [{dueDate:'2030-02-30'},{description:'x'.repeat(4001)},{category:'made-up-module'},{priority:'not-a-priority'}])assert.equal((await f.call(path(b)+'/records','POST',rec(extra))).status,400);assert.equal(f.app.workspace.tasks(b).length,0);}finally{await f.close();}});
test('task status is versioned and cannot be updated through another building',async()=>{const f=await harness();try{const a=(await f.start()).data.building.id,b=(await f.start({name:'Other'})).data.building.id,record=(await f.call(path(a)+'/records','POST',rec())).data.records[0];assert.equal((await f.call(path(b)+'/records/'+record.id,'PATCH',{version:1,status:'closed'})).status,404);const r=await f.call(path(a)+'/records/'+record.id,'PATCH',{version:1,status:'closed'});assert.equal(r.data.summary.open,0);assert.equal((await f.call(path(a)+'/records/'+record.id,'PATCH',{version:1,status:'open'})).status,409);assert.equal((await f.call(path(a)+'/records/'+record.id,'PATCH',{version:2,status:'compliant'})).status,400);}finally{await f.close();}});
test('legacy task updates are reflected in the same tracking record',async()=>{const f=await harness();try{const b=(await f.start()).data.building.id,r=(await f.call(path(b)+'/records','POST',rec())).data.records[0];f.app.workspace.updateTask(r.id,{version:1,status:'in_progress'});const state=(await f.call(path(b))).data;assert.equal(state.records[0].status,'in_progress');assert.equal(state.records[0].version,2);}finally{await f.close();}});
test('paused category retains every record and due dates stay visible',async()=>{const f=await harness();try{const b=(await f.start()).data.building.id,r=await f.call(path(b)+'/records','POST',rec({dueDate:'2020-01-01'})),setting=r.data.categories.find(c=>c.id==='water');const off=await f.call(path(b)+'/modules/water','PUT',{version:setting.version,enabled:false});assert.equal(off.data.records.length,1);assert.equal(off.data.summary.overdue,1);}finally{await f.close();}});
test('workspace settings, manual tasks and preview survive restart without new inference',async()=>{const f=await harness();try{const start=(await f.start()).data,b=start.building.id;await f.call(path(b)+'/records','POST',rec());await f.restart();const r=(await f.call(path(b))).data;assert.equal(r.preview.id,start.preview.id);assert.equal(r.records.length,1);assert.equal(r.summary.enabled,1);assert.equal(f.app.workspace.locations(b).length,0);}finally{await f.close();}});
test('one-page routes serve the same app and retained specialist routes remain accessible',async()=>{const f=await harness();try{const a=await(await fetch(f.base+'/start')).text();for(const p of ['/','/build?building=example','/instant'])assert.equal(await(await fetch(f.base+p)).text(),a);assert.match(a,/id="tracking-grid"/);assert.match(a,/id="optional-name"/);assert.match(a,/id="model-settings"/);for(const p of ['/admin','/advanced-build','/photo-tools','/workspace-ui.js','/workspace.css','/modules/domain/tracking.mjs'])assert.equal((await fetch(f.base+p)).status,200);}finally{await f.close();}});
test('configuration and dashboard reads do not enable categories or trigger processing',async()=>{const f=await harness();try{const b=(await f.start()).data.building.id;for(let i=0;i<3;i++){await f.call(path(b));await f.call('/api/workspace/buildings');}assert.equal(f.app.workspace.db.prepare('SELECT count(*) AS n FROM workspace_modules').get().n,0);assert.equal(trackingCategories.length,12);}finally{await f.close();}});
