import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openWorkspace } from '../apps/api/database.mjs';
import { createApp } from '../apps/api/server.mjs';
import { createEquipmentDemo } from '../apps/api/management/equipment-demo.mjs';
import { generateDemo, equipmentTypes, openIssue, demoCounts, NOTICE } from '../packages/equipment-demo/model.mjs';
import { compileSurfaces } from '../packages/viewer/surfaces.mjs';
import { equipmentMesh, placeEquipment, buildEquipmentGroups, equipmentGLB } from '../packages/equipment-demo/geometry.mjs';
const floor={id:0,key:'GF',name:'Synthetic floor',y:0};
const locations=[{id:'fixture-corridor',title:'Synthetic corridor',type:'space',floor_key:'GF',building_id:'marketfield',basis:'drawing-derived'},{id:'fixture-lobby',title:'Synthetic entrance lobby',type:'space',floor_key:'GF',building_id:'marketfield'},{id:'fixture-plant',title:'Synthetic plant room',type:'space',floor_key:'GF',building_id:'marketfield'},{id:'fixture-flat',title:'Flat 1',type:'space',floor_key:'GF',building_id:'marketfield'},{id:'fixture-void',title:'Void',type:'void',floor_key:'GF',building_id:'marketfield'},{id:'foreign',title:'Other corridor',type:'space',floor_key:'GF',building_id:'another'}];
const topics=[{id:'cleaning-area',label:'Communal area',category:'cleaning',tags:['corridor'],scope:'Fictional scoping prompt'},{id:'finance-contract',label:'Contract',category:'finance',tags:['building'],scope:'Fictional contract prompt'},{id:'fire-panel',label:'Alarm system records',category:'fire',tags:['plant'],scope:'Fictional system prompt'}];
const clock=()=>new Date('2026-09-29T12:00:00Z');
const input=()=>({locations,floors:[floor],topics,today:'2026-09-29'});
function fixture(){const ws=openWorkspace(':memory:','/no-files');ws.db.prepare('INSERT INTO buildings VALUES(?,?,?,?,?,?,?)').run('marketfield','Synthetic fixture','','','marketfield','TEST',clock().toISOString());for(const l of locations.filter(l=>l.building_id==='marketfield'))ws.db.prepare('INSERT INTO locations(id,building_id,title,type,floor_key,source,basis,summary) VALUES(?,?,?,?,?,?,?,?)').run(l.id,'marketfield',l.title,l.type,l.floor_key,'TEST','unconfirmed','Synthetic fixture');ws.manifest={floors:[floor]};const service=createEquipmentDemo({workspace:ws,clock,loadTopics:async()=>topics});return {ws,service};}
const plan=()=>({floors:[floor],assets:[{id:'fixture-corridor',title:'Synthetic entrance lobby',type:'space',floor:0,pos:[5,5]}],objects:[],shapes:[{f:0,kind:'slab',y:0,h:.2,p:[[0,0],[12,0],[12,12],[0,12]],holes:[[[9,9],[11,9],[11,11],[9,11]]]}],segments:[{f:0,kind:'partition',y:0,h:2.8,w:.15,a:[1,0],b:[1,12]}]});
const object=(style='alarm-panel',slot=0)=>({id:'demo-equipment-test-'+style,style,locationId:'fixture-corridor',slot});
test('all catalogue topics are represented as unassessed scope, not automatically detected faults',()=>{const d=generateDemo(input());assert.equal(d.records.filter(r=>r.kind==='scope').length,topics.length);assert.ok(d.records.every(r=>r.demo));assert.match(d.notice,/DEMONSTRATION/);assert.ok(d.records.filter(r=>r.kind==='scope').every(r=>r.status==='not_assessed'&&!openIssue(r)));});
test('fictional equipment includes alarm, lighting, utilities and communal objects',()=>{const d=generateDemo(input());for(const t of equipmentTypes)assert.ok(d.records.some(r=>r.style===t.id),t.id);assert.equal(equipmentTypes.length,30);assert.ok(d.objects.every(o=>o.demo&&!('x'in o)&&!('pos'in o)));});
test('communal areas are included, but flats and voids are not labelled communal',()=>{const d=generateDemo(input());assert.equal(d.records.filter(r=>r.kind==='area').length,3);assert.ok(!d.records.some(r=>r.locationId==='fixture-void'||r.locationId==='foreign'));assert.ok(d.records.some(r=>r.locationId==='fixture-flat'&&r.kind==='reference'));});
test('upcoming scope and normal equipment do not become issue markers',()=>{const d=generateDemo(input());assert.ok(d.records.filter(openIssue).every(r=>r.kind==='issue'));const i=d.records.find(openIssue);i.status='resolved';assert.equal(openIssue(i),false);assert.ok(demoCounts(d).topics===3);});
test('generation is deterministic and does not mutate source locations',()=>{const x=input(),before=JSON.stringify(x);assert.deepEqual(generateDemo(x),generateDemo(x));assert.equal(JSON.stringify(x),before);});
test('model-less scope does not invent room positions',()=>{const d=generateDemo({locations:[],floors:[],topics,today:'2026-09-29'});assert.equal(d.objects.length,0);assert.ok(d.records.every(r=>!r.locationId));});
test('large and invalid request scope is bounded',()=>{assert.throws(()=>generateDemo({...input(),topics:Array(501).fill(topics[0])}));assert.throws(()=>generateDemo({...input(),today:'not-a-date'}));});
for(const type of equipmentTypes)test('finite outward triangle geometry: '+type.id,()=>{const d=equipmentMesh(type.id);assert.ok(d.length>300&&d.length<80000);assert.equal(d.length%30,0);assert.ok(d.every(Number.isFinite));for(let i=0;i<d.length;i+=30){const a=[d[i],d[i+1],d[i+2]],b=[d[i+10],d[i+11],d[i+12]],c=[d[i+20],d[i+21],d[i+22]],u=b.map((v,j)=>v-a[j]),v=c.map((v,j)=>v-a[j]),n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]];assert.ok(n.reduce((s,v,j)=>s+v*d[i+3+j],0)>-1e-6);}});
test('unknown equipment is rejected',()=>assert.throws(()=>equipmentMesh('remote-url')));
test('placement preserves source geometry and never uses absent model anchors',()=>{const p=plan(),before=JSON.stringify(p);const result=placeEquipment(p,[object(),{...object('pump'),locationId:'missing'}],compileSurfaces(p));assert.equal(result.placed.length,1);assert.equal(result.unplaced.length,1);assert.equal(JSON.stringify(p),before);});
test('position selection respects source holes and display spacing',()=>{const result=placeEquipment(plan(),[object(),object('call-point',1),object('pump',2)],compileSurfaces(plan()));assert.ok(result.placed.length>=2);for(const a of result.placed){assert.ok(a.x>=0&&a.x<12&&a.z>=0&&a.z<12);assert.ok(!(a.x>9&&a.x<11&&a.z>9&&a.z<11));for(const b of result.placed)if(a!==b)assert.ok(Math.hypot(a.x-b.x,a.z-b.z)>.4);}});
test('display wall-height settings never shrink or flatten equipment',()=>{for(const t of equipmentTypes){const input=[{...object(t.id),floor:0,floorY:0,x:4,z:4,rotation:.6,mount:t.mount}],a=buildEquipmentGroups(input,{size:2,capFloor:0,wallHeight:1.05})[0],b=buildEquipmentGroups(input,{size:2,capFloor:0,wallHeight:2.8})[0];assert.deepEqual(a.vertices,b.vertices,t.id);assert.ok(a.bounds.lo[1]>=0);assert.ok(a.vertices.every(Number.isFinite));}});
test('separate demo GLB includes provenance and no texture or external resource',()=>{const groups=buildEquipmentGroups(placeEquipment(plan(),[object(),object('pump',1)],compileSurfaces(plan())).placed);const bytes=equipmentGLB(groups),v=new DataView(bytes.buffer);assert.equal(v.getUint32(0,true),0x46546c67);assert.equal(v.getUint32(8,true),bytes.length);const doc=JSON.parse(new TextDecoder().decode(bytes.subarray(20,20+v.getUint32(12,true))));assert.equal(doc.extras.demonstration,true);assert.ok(doc.nodes.every(n=>n.extras.demo));assert.ok(!doc.images);assert.equal(doc.buffers[0].byteLength,bytes.length-28-v.getUint32(12,true));});
test('reading a new demonstration creates no population and leaves real data alone',()=>{const f=fixture();try{assert.equal(f.service.read().initialized,false);assert.equal(f.ws.tasks('marketfield').length,0);assert.equal(f.ws.events('marketfield').length,0);}finally{f.ws.close();}});
test('initialization is explicit, idempotent and separate from real records',async()=>{const f=fixture();try{await assert.rejects(f.service.initialize({}),e=>e.status===400);const a=await f.service.initialize({demonstration:true}),b=await f.service.initialize({demonstration:true});assert.equal(a.records.length,b.records.length);assert.equal(b.version,1);assert.equal(f.ws.tasks('marketfield').length,0);assert.equal(f.ws.documents('marketfield').length,0);assert.equal(f.ws.events('marketfield').length,0);}finally{f.ws.close();}});
test('missing model refuses seed instead of substituting generic building',async()=>{const f=fixture();try{f.ws.manifest=null;await assert.rejects(f.service.initialize({demonstration:true}),e=>e.status===409);assert.equal(f.service.read().initialized,false);}finally{f.ws.close();}});
test('demo issue resolution changes only fictional state and rejects stale writes',async()=>{const f=fixture();try{let d=await f.service.initialize({demonstration:true});const issue=d.records.find(openIssue);d=f.service.update({id:issue.id,status:'resolved',note:'Simulated repair only',version:1});assert.equal(d.version,2);assert.equal(openIssue(d.records.find(r=>r.id===issue.id)),false);assert.throws(()=>f.service.update({id:issue.id,status:'open',note:'stale',version:1}),e=>e.status===409);assert.equal(f.ws.tasks('marketfield').length,0);}finally{f.ws.close();}});
test('demo updates cannot manufacture an accepted real asset status or alter coordinates',async()=>{const f=fixture();try{const d=await f.service.initialize({demonstration:true}),a=d.records.find(r=>r.kind==='equipment');assert.throws(()=>f.service.update({id:a.id,status:'site_observed',note:'bad',version:1}),e=>e.status===400);assert.throws(()=>f.service.update({id:'real-record',status:'resolved',note:'bad',version:1}),e=>e.status===404);assert.equal(f.service.read().version,1);}finally{f.ws.close();}});
test('reset needs explicit confirmation and correct version and never clears real tables',async()=>{const f=fixture();try{await f.service.initialize({demonstration:true});assert.throws(()=>f.service.reset({confirm:'yes',version:1}),e=>e.status===409);assert.equal(f.service.reset({confirm:'RESET DEMO',version:1}).initialized,false);assert.equal(f.ws.locations('marketfield').length,5);assert.equal(f.ws.buildings().length,1);}finally{f.ws.close();}});
test('actual HTTP requires sessions and CSRF; static demo module does not seed data',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'pc-demo-http-'));const app=createApp({dataDir:dir,assetsDir:join(dir,'absent'),equipmentDemo:{loadTopics:async()=>topics}});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;
 try{assert.equal((await fetch(base+endpoint())).status,401);const response=await fetch(base+'/api/session'),session=await response.json(),cookie=response.headers.get('set-cookie').split(';')[0],headers={Cookie:cookie,Origin:base,'Content-Type':'application/json','X-CSRF-Token':session.csrf};
  assert.equal((await fetch(base+endpoint(),{headers})).status,200);assert.equal((await fetch(base+endpoint(),{method:'POST',headers:{...headers,'X-CSRF-Token':'bad'},body:JSON.stringify({demonstration:true})})).status,403);
  assert.equal((await fetch(base+endpoint(),{method:'POST',headers,body:JSON.stringify({demonstration:true})})).status,409);
  for(const path of ['/equipment-demo.js','/equipment-demo.css','/equipment-viewer.js','/equipment-viewer.css','/modules/equipment-demo/model.mjs','/modules/equipment-demo/geometry.mjs']){const r=await fetch(base+path);assert.equal(r.status,200,path);assert.ok((await r.text()).length>100);}
  const status=await (await fetch(base+endpoint(),{headers})).json();assert.equal(status.initialized,false);assert.equal(app.workspace.buildings().length,0);
 }finally{await app.close();await rm(dir,{recursive:true,force:true});}
 function endpoint(){return '/api/equipment-demo';}
});
test('demo survives restart separately from the real task register',async()=>{const dir=await mkdtemp(join(tmpdir(),'pc-demo-persist-'));try{let w=openWorkspace(join(dir,'x.db'),join(dir,'none')),s=createEquipmentDemo({workspace:w});w.db.prepare('INSERT INTO marketfield_equipment_demo VALUES(1,1,?)').run(JSON.stringify(generateDemo(input())));w.close();w=openWorkspace(join(dir,'x.db'),join(dir,'none'));s=createEquipmentDemo({workspace:w});assert.ok(s.read().records.length>0);assert.equal(w.tasks().length,0);w.close();}finally{await rm(dir,{recursive:true,force:true});}});

test('current-main default loader covers every real tracking-library topic',async t=>{
 let library;try{library=await import('../packages/management/tracking-library.mjs');}catch(e){if(e.code==='ERR_MODULE_NOT_FOUND')return t.skip('The older local code artifact lacks the later tracking catalogue; full current-main CI must run this test.');throw e;}
 const f=fixture();try{const s=createEquipmentDemo({workspace:f.ws,clock}),d=await s.initialize({demonstration:true});assert.equal(library.trackingItems.length,171);assert.equal(d.counts.topics,library.trackingItems.length);for(const item of library.trackingItems){const r=d.records.find(r=>r.topicId===item.id);assert.ok(r);assert.ok(r.notes.startsWith(item.scope));assert.equal(r.status,'not_assessed');}}finally{f.ws.close();}
});
test('template placement does not add equipment to private flat or door references',()=>{const d=generateDemo(input());assert.ok(!d.objects.some(o=>o.locationId==='fixture-flat'));const door={id:'fixture-door',building_id:'marketfield',title:'Flat entrance door',type:'door',floor_key:'GF'};assert.ok(!generateDemo({...input(),locations:[...locations,door]}).objects.some(o=>o.locationId===door.id));});
test('blank simulation notes are rejected and simulation status cannot enter real workflow states',async()=>{const f=fixture();try{const d=await f.service.initialize({demonstration:true}),id=d.records.find(openIssue).id;for(const status of ['site_observed','closed','accepted'])assert.throws(()=>f.service.update({id,status,version:1,note:'Simulation'}),e=>e.status===400);assert.throws(()=>f.service.update({id,status:'resolved',version:1,note:''}),e=>e.status===400);assert.equal(f.service.read().version,1);}finally{f.ws.close();}});
