import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdtemp,rm,mkdir,writeFile,readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { request as httpRequest } from 'node:http';
import { openWorkspace } from '../apps/api/database.mjs';
import { createManagement,advanceDate,validDate,moneyPence,localDay } from '../apps/api/management/service.mjs';
import { createPreviewApp } from '../apps/api/preview-server.mjs';
import { categories,kinds,templates } from '../packages/management/catalog.mjs';
const time=()=>new Date('2026-09-29T10:30:00Z'),key=()=>randomUUID();
function fixture(){const ws=openWorkspace(':memory:','/no-private-files');const m=createManagement({workspace:ws,clock:time});m.open();const other=ws.addBuilding({name:'Synthetic other building',postcode:'AA1 1AA',address:'Test only'});ws.db.prepare('INSERT INTO locations(id,building_id,title,type,floor_key,source,basis,summary) VALUES(?,?,?,?,?,?,?,?)').run('test-location','marketfield','Synthetic door','door','UGF','TEST-PLAN','estimated','Fixture, not Marketfield geometry.');ws.db.prepare('INSERT INTO locations(id,building_id,title,type,floor_key,source,basis,summary) VALUES(?,?,?,?,?,?,?,?)').run('other-location',other.id,'Other space','room','GF','TEST','estimated','Fixture');return {ws,m,other,bid:'marketfield'};}
const asset=(f,extra={})=>f.m.add(f.bid,{kind:'asset',title:'Synthetic pump',category:'water',requestKey:key(),...extra});
const work=(f,extra={})=>f.m.add(f.bid,{kind:'work',title:'Synthetic repair',category:'repairs',requestKey:key(),...extra});
const schedule=(f,extra={})=>f.m.add(f.bid,{kind:'schedule',title:'Synthetic programme',category:'other',dueDate:'2026-08-31',data:{intervalUnit:'months',interval:1,basisType:'manager_programme',basisReference:'Synthetic routine agreed in test, not a legal schedule.'},requestKey:key(),...extra});
const fails=(fn,status=400)=>assert.throws(fn,e=>e.status===status);

test('management opens without a model but invents no assets or compliance status',()=>{const f=fixture();const s=f.m.snapshot(f.bid);assert.equal(s.modelInstalled,false);assert.equal(s.records.length,0);assert.equal(s.summary.assets,0);assert.equal(s.attention.length,0);assert.equal(s.summary.overdue,0);assert.ok(f.m.catalog().boundary.includes('No live sensors'));f.m.open();assert.equal(f.ws.buildings().filter(b=>b.id===f.bid).length,1);f.ws.close();});
test('catalogue covers all 18 requested domains plus custom responsibilities',()=>{assert.equal(categories.length,19);assert.equal(new Set(categories.map(c=>c.id)).size,19);assert.ok(categories.some(c=>c.id==='residents'));assert.ok(categories.some(c=>c.id==='safety'));assert.ok(categories.some(c=>c.id==='other'));assert.equal(Object.keys(kinds).length,10);for(const t of templates)assert.equal(t.dueDate,undefined);});
test('strict calendar validation and London boundary',()=>{for(const d of ['2025-02-30','2025-13-01','2025-00-01','not-a-date','1800-01-01'])fails(()=>validDate(d));assert.equal(validDate('2024-02-29'),'2024-02-29');assert.equal(localDay(new Date('2026-09-28T23:30:00Z')),'2026-09-29');});
test('calendar recurrence handles short months and does not drift the anchor',()=>{assert.equal(advanceDate('2026-01-31','months',1,31),'2026-02-28');assert.equal(advanceDate('2026-02-28','months',1,31),'2026-03-31');assert.equal(advanceDate('2024-02-28','days',1),'2024-02-29');assert.equal(advanceDate('2026-01-31','none',1),'');});
test('monetary amounts use exact pence and reject negative and extra precision',()=>{assert.equal(moneyPence('0.10')+moneyPence('0.20'),30);assert.equal(moneyPence('100.5'),10050);for(const x of ['-1','1e5','NaN','1.333','100000000'])fails(()=>moneyPence(x));});
test('every record kind can be saved, read and edited without hidden user data',()=>{const f=fixture();for(const kind of Object.keys(kinds)){const data=kind==='schedule'?{basisReference:'Defined by test programme'}:kind==='cost'?{amount:'12.55'}:kind==='responsibility'?{scope:'Only the test part of this building'}:kind==='incident'?{interimMeasures:'Isolated by the operator in a test'}:{};const r=f.m.add(f.bid,{kind,title:'Synthetic '+kind,category:'other',dueDate:'2026-10-15',data,requestKey:key()});assert.equal(r.version,1);const up=f.m.update(f.bid,r.id,{version:1,notes:'Changed note',requestKey:key()});assert.equal(up.version,2);assert.equal(f.m.history(f.bid,r.id).length,2);}assert.equal(f.m.snapshot(f.bid).records.length,10);f.ws.close();});
test('idempotent creation returns original record and rejects changed payload',()=>{const f=fixture(),body={kind:'asset',title:'Unique asset',requestKey:key()};const a=f.m.add(f.bid,body),b=f.m.add(f.bid,body);assert.equal(a.id,b.id);assert.equal(f.m.snapshot(f.bid).records.length,1);fails(()=>f.m.add(f.bid,{...body,title:'Changed'}),409);f.ws.close();});
test('stale writes and cross-building references are rejected atomically',()=>{const f=fixture(),r=asset(f);f.m.update(f.bid,r.id,{version:1,title:'Changed',requestKey:key()});fails(()=>f.m.update(f.bid,r.id,{version:1,title:'Lost update',requestKey:key()}),409);fails(()=>asset(f,{locationId:'other-location'}));fails(()=>f.m.read(f.other.id,r.id),404);fails(()=>f.m.update(f.other.id,r.id,{version:2,requestKey:key()}),404);assert.equal(f.m.read(f.bid,r.id).title,'Changed');f.ws.close();});
test('observed assets require a checker date and evidence, never generated from model locations',()=>{const f=fixture();fails(()=>asset(f,{data:{basis:'site_observed'}}));const a=asset(f,{locationId:'test-location',data:{basis:'drawing_derived'}});assert.equal(a.status,'unconfirmed');assert.equal(f.m.snapshot(f.bid).summary.unconfirmedAssets,1);const b=asset(f,{data:{basis:'site_observed',verifiedBy:'Test operator',verifiedOn:'2026-09-28'},evidenceReference:'Inspection record TEST-001'});assert.equal(b.data.basis,'site_observed');assert.equal(f.ws.locations(f.bid).length,1);f.ws.close();});
test('evidence and asset references are scoped to the building',()=>{const f=fixture(),d=f.ws.addDocument(f.other.id,{name:'test.pdf',mime:'application/pdf',size:10,storageName:'test',sha256:'abc'});fails(()=>asset(f,{evidenceIds:[d.id]}));const a=f.m.add(f.other.id,{kind:'asset',title:'Other asset',requestKey:key()});fails(()=>work(f,{assetId:a.id}),404);const w=work(f);fails(()=>work(f,{assetId:w.id}));f.ws.close();});
test('no direct completion or arbitrary kind changes are allowed',()=>{const f=fixture();fails(()=>work(f,{status:'closed'}));const w=work(f);fails(()=>f.m.update(f.bid,w.id,{version:1,status:'closed',requestKey:key()}));fails(()=>f.m.update(f.bid,w.id,{version:1,kind:'asset',requestKey:key()}));fails(()=>f.m.action(f.bid,w.id,{version:1,action:'accept',reviewer:'Test',notes:'OK',requestKey:key()}),409);assert.equal(f.m.history(f.bid,w.id).length,1);f.ws.close();});
test('completion and evidence acceptance are separate with full retained history',()=>{const f=fixture(),w=work(f);fails(()=>f.m.action(f.bid,w.id,{action:'submit',version:1,notes:'done',requestKey:key()}));const payload={action:'submit',version:1,notes:'Repaired in synthetic test',evidenceReference:'Test report TEST-99 and photographs held separately',requestKey:key()};const submitted=f.m.action(f.bid,w.id,payload);assert.equal(submitted.status,'awaiting_review');assert.equal(f.m.action(f.bid,w.id,payload).version,2);assert.equal(f.m.snapshot(f.bid).summary.awaitingReview,1);const done=f.m.action(f.bid,w.id,{action:'accept',version:2,reviewer:'Test reviewer',notes:'Evidence checked in test',requestKey:key()});assert.equal(done.status,'closed');assert.ok(done.completion.reviewedAt);const reopened=f.m.action(f.bid,w.id,{action:'reopen',version:3,notes:'Test issue returned',requestKey:key()});assert.equal(reopened.status,'reported');assert.equal(f.m.history(f.bid,w.id).length,4);f.ws.close();});
test('failed access, defects and skips do not advance inspection dates',()=>{const f=fixture();let s=schedule(f);for(const outcome of ['no_access','defect','skipped']){s=f.m.check(f.bid,s.id,{version:s.version,dueFor:s.dueDate,checkedOn:'2026-09-28',outcome,notes:'Synthetic recorded outcome',requestKey:key()});assert.equal(s.dueDate,'2026-08-31');assert.equal(s.lastCheck.outcome,outcome);}assert.equal(f.m.snapshot(f.bid).checks.length,3);assert.equal(f.m.snapshot(f.bid).summary.overdue,1);f.ws.close();});
test('accepted check advances one occurrence, keeps anchor, and preserves no-access history',()=>{const f=fixture();let s=schedule(f,{dueDate:'2026-07-31'});fails(()=>f.m.check(f.bid,s.id,{version:1,dueFor:s.dueDate,checkedOn:'2026-09-28',outcome:'completed',notes:'test',requestKey:key()}));const input={version:1,dueFor:s.dueDate,checkedOn:'2026-09-28',outcome:'completed',reviewer:'Test reviewer',notes:'Report reviewed',evidenceReference:'Report TEST-122',requestKey:key()};s=f.m.check(f.bid,s.id,input);assert.equal(s.dueDate,'2026-08-31');assert.equal(f.m.snapshot(f.bid).summary.overdue,1);assert.equal(f.m.check(f.bid,s.id,input).version,2);assert.equal(f.m.snapshot(f.bid).checks.length,1);f.ws.close();});
test('future check, stale occurrence and invalid schedule interval fail',()=>{const f=fixture(),s=schedule(f);fails(()=>f.m.check(f.bid,s.id,{version:1,dueFor:s.dueDate,checkedOn:'2026-10-01',outcome:'no_access',notes:'test',requestKey:key()}));fails(()=>f.m.check(f.bid,s.id,{version:1,dueFor:'2025-01-01',checkedOn:'2026-09-28',outcome:'no_access',notes:'test',requestKey:key()}),409);fails(()=>schedule(f,{dueDate:''}));fails(()=>schedule(f,{data:{basisReference:'Test',intervalUnit:'months',interval:200}}));assert.equal(f.m.snapshot(f.bid).checks.length,0);f.ws.close();});
test('one-off check pauses after explicit evidenced completion',()=>{const f=fixture(),s=schedule(f,{data:{intervalUnit:'none',interval:1,basisReference:'One-off test'}});const done=f.m.check(f.bid,s.id,{version:1,dueFor:s.dueDate,checkedOn:'2026-09-28',outcome:'completed',reviewer:'Test reviewer',notes:'Complete',evidenceReference:'Report TEST-199',requestKey:key()});assert.equal(done.status,'paused');assert.equal(done.dueDate,'');f.ws.close();});
test('document supersession preserves files and revisions; self-supersession rolls back',()=>{const f=fixture(),d=f.m.add(f.bid,{kind:'document',title:'Drawing A',status:'current',evidenceReference:'Original drawing TEST-A',data:{revision:'A'},requestKey:key()});const v=f.m.add(f.bid,{kind:'document',title:'Drawing B',status:'current',evidenceReference:'Updated drawing TEST-B',data:{revision:'B',supersedesId:d.id},requestKey:key()});assert.equal(f.m.read(f.bid,d.id).status,'superseded');fails(()=>f.m.update(f.bid,v.id,{version:1,data:{supersedesId:v.id},requestKey:key()}));assert.equal(f.m.read(f.bid,v.id).version,1);assert.equal(f.m.history(f.bid,d.id).length,2);f.ws.close();});
test('cost states remain separate; amount precision and paid references enforced',()=>{const f=fixture();for(const status of ['forecast','quotation','committed','paid'])f.m.add(f.bid,{kind:'cost',title:'Cost '+status,status,data:{amount:'123.45',reference:'TEST-001',paidOn:'2026-09-28'},requestKey:key()});assert.deepEqual(f.m.snapshot(f.bid).summary.costs,{forecast:12345,quotation:12345,committed:12345,paid:12345});fails(()=>f.m.add(f.bid,{kind:'cost',title:'Unsupported',status:'paid',data:{amount:'100'},requestKey:key()}));f.ws.close();});
test('dashboard includes outage, evidence, deadline, expiry and contract notice prompts',()=>{const f=fixture();asset(f,{status:'out_of_service'});f.m.add(f.bid,{kind:'incident',title:'Synthetic outage',data:{interimMeasures:'Operator aware',notificationDeadline:'2026-09-28T10:00'},requestKey:key()});f.m.add(f.bid,{kind:'document',title:'Certificate test',status:'current',evidenceReference:'CERT-TEST-01',data:{expiresOn:'2026-09-01'},requestKey:key()});f.m.add(f.bid,{kind:'contract',title:'Contract test',status:'active',data:{noticeOn:'2026-09-01',endsOn:'2026-09-20'},requestKey:key()});const reasons=f.m.snapshot(f.bid).attention.flatMap(a=>a.reasons);for(const item of ['Out of service','Incident / outage open','Document expired','Contract notice date reached','Recorded notification deadline passed','Contract end date passed'])assert.ok(reasons.includes(item),item);f.ws.close();});
test('export includes history and checks but excludes file storage names and keys',()=>{const f=fixture();asset(f);f.ws.addDocument(f.bid,{name:'Fixture PDF',mime:'application/pdf',size:10,storageName:'secret-storage-name',sha256:'private-hash'});const exp=f.m.export(f.bid),body=JSON.stringify(exp);assert.equal(exp.recordHistory.length,1);assert.ok(!body.includes('secret-storage-name'));assert.ok(!body.includes('private-hash'));assert.match(exp.note,/not a file backup/);f.ws.close();});
test('record persistence survives a restart without rescheduling or adding samples',async()=>{const dir=await mkdtemp(join(tmpdir(),'pc-management-persist-'));try{let ws=openWorkspace(join(dir,'workspace.sqlite'),join(dir,'none')),m=createManagement({workspace:ws,clock:time});m.open();const r=m.add('marketfield',{kind:'asset',title:'Persisted fixture',requestKey:key()});ws.close();ws=openWorkspace(join(dir,'workspace.sqlite'),join(dir,'none'));m=createManagement({workspace:ws,clock:time});assert.equal(m.snapshot('marketfield').records.length,1);assert.equal(m.read('marketfield',r.id).title,r.title);assert.equal(m.history('marketfield',r.id).length,1);ws.close();}finally{await rm(dir,{recursive:true,force:true});}});

async function httpFixture(fn){const dir=await mkdtemp(join(tmpdir(),'pc-management-http-'));const app=createPreviewApp({dataDir:dir,assetsDir:join(dir,'none'),management:{clock:time},preview:{research:{configured:()=>false}},photoFlow:{research:{configured:()=>false},maps:{enabled:()=>false}}});await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+app.server.address().port;try{const session=await fetch(base+'/api/session'),s=await session.json(),headers={'Cookie':session.headers.get('set-cookie').split(';')[0],'X-CSRF-Token':s.csrf,'Origin':base,'Content-Type':'application/json'};const call=(path,method='GET',body,extra={})=>fetch(base+path,{method,headers:{...headers,...extra},...(body!==undefined?{body:JSON.stringify(body)}:{})});await fn({dir,app,base,headers,call});}finally{await app.close();await rm(dir,{recursive:true,force:true});}}
test('HTTP workspace and static assets serve with security headers and no provider use',()=>httpFixture(async({call,base})=>{for(const path of ['/marketfield','/marketfield/','/management.css','/management.js','/modules/management/catalog.mjs']){const r=await fetch(base+path);assert.equal(r.status,200,path);assert.match(r.headers.get('content-security-policy'),/default-src 'self'/);assert.equal(r.headers.get('cache-control'),'no-store');assert.ok((await r.text()).length>100);}const bootstrap=await call('/api/management/bootstrap');assert.equal((await bootstrap.json()).exists,false);assert.equal((await call('/api/management/open','POST',{})).status,200);const data=await (await call('/api/management/buildings/marketfield')).json();assert.equal(data.records.length,0);assert.equal(data.modelInstalled,false);}));
test('management API enforces session, origin and CSRF on writes',()=>httpFixture(async({call,base})=>{assert.equal((await fetch(base+'/api/management/catalog')).status,401);assert.equal((await call('/api/management/open','POST',{}, {'X-CSRF-Token':'wrong'})).status,403);assert.equal((await call('/api/management/open','POST',{}, {Origin:'https://other.example'})).status,403);const status=await new Promise((resolve,reject)=>{const r=httpRequest(base+'/marketfield',{headers:{Host:'untrusted.example'}},res=>{res.resume();resolve(res.statusCode)});r.on('error',reject);r.end();});assert.equal(status,403);}));
test('real API saves evidence-linked work and reviewer acceptance with history',()=>httpFixture(async({call,app})=>{await call('/api/management/open','POST',{});const base='/api/management/buildings/marketfield';let r=await (await call(base+'/records','POST',{kind:'work',title:'HTTP test work',requestKey:key()})).json();const saved=await call(base+'/records/'+r.id+'/action','POST',{action:'submit',version:r.version,notes:'Test completed',evidenceReference:'HTTP-TEST-REPORT',requestKey:key()});assert.equal(saved.status,200);r=await saved.json();assert.equal(r.status,'awaiting_review');r=await (await call(base+'/records/'+r.id+'/action','POST',{action:'accept',version:r.version,reviewer:'HTTP reviewer',notes:'Report checked',requestKey:key()})).json();assert.equal(r.status,'closed');const history=await (await call(base+'/records/'+r.id+'/history')).json();assert.equal(history.length,3);assert.equal(app.workspace.tasks('marketfield').length,0,'old work records not overwritten');const exp=await call(base+'/export');assert.match(exp.headers.get('content-disposition'),/attachment/);}));
test('real PDF upload can link to current document record, without auto inspection',()=>httpFixture(async({call,base,headers})=>{await call('/api/management/open','POST',{});const upload=await fetch(base+'/api/buildings/marketfield/documents',{method:'POST',headers:{...headers,'Content-Type':'application/pdf','X-File-Name':'synthetic.pdf'},body:Buffer.from('%PDF-1.4\n% synthetic upload fixture only')});assert.equal(upload.status,201);const d=await upload.json();const r=await call('/api/management/buildings/marketfield/records','POST',{kind:'document',title:'Evidence fixture',status:'current',evidenceIds:[d.id],requestKey:key()});assert.equal(r.status,201);const download=await call('/api/documents/'+d.id);assert.equal(download.status,200);assert.match(download.headers.get('content-disposition'),/attachment/);}));
test('Marketfield manifest linkage uses source locations only, not seeded assets',async()=>{const dir=await mkdtemp(join(tmpdir(),'pc-management-manifest-'));try{const path=join(dir,'assets','marketfield');await mkdir(path,{recursive:true});const manifest={meta:{},floors:[{id:0,key:'GF',name:'Synthetic floor'}],assets:[{id:'DEMO-ONLY',title:'Synthetic reference',type:'door',floor:0,source:'TEST',basis:'estimated',summary:'Not an installed asset'}],sources:[]};await writeFile(join(path,'manifest.json'),JSON.stringify(manifest));const ws=openWorkspace(':memory:',join(dir,'assets')),m=createManagement({workspace:ws,clock:time});const data=m.snapshot('marketfield');assert.equal(data.modelInstalled,true);assert.equal(data.locations[0].id,'DEMO-ONLY');assert.equal(data.records.length,0);ws.close();}finally{await rm(dir,{recursive:true,force:true});}});
test('customer screen contains all workflows but no generated readings or public API calls',async()=>{const html=await readFile(new URL('../apps/web/public/management/index.html',import.meta.url),'utf8'),js=await readFile(new URL('../apps/web/public/management/app.js',import.meta.url),'utf8');for(const s of ['Marketfield model','Work &amp; checks','Documents','Costs &amp; contracts','People &amp; safety'])assert.ok(html.includes(s));assert.doesNotMatch(html,/<script[^>]+https?:/);assert.doesNotMatch(js,/api\.openai|fetch\(['"]https?:/);assert.match(js,/event\.origin!==location\.origin/);assert.match(js,/event\.source!==\$\('model'\)\.contentWindow/);assert.match(js,/escapeHtml/);} );
test('document revision cycles are rejected without changing either current record',()=>{const f=fixture(),a=f.m.add(f.bid,{kind:'document',title:'Revision A',status:'current',evidenceReference:'Report TEST-A',requestKey:key()}),b=f.m.add(f.bid,{kind:'document',title:'Revision B',status:'current',evidenceReference:'Report TEST-B',data:{supersedesId:a.id},requestKey:key()});fails(()=>f.m.update(f.bid,a.id,{version:2,status:'current',data:{supersedesId:b.id},requestKey:key()}));assert.equal(f.m.read(f.bid,a.id).status,'superseded');assert.equal(f.m.read(f.bid,b.id).status,'current');f.ws.close();});
test('paused schedules, retired assets and void costs preserve their history',()=>{const f=fixture(),s=schedule(f),a=asset(f),c=f.m.add(f.bid,{kind:'cost',title:'Test cost',status:'forecast',data:{amount:'10.00'},requestKey:key()});f.m.update(f.bid,s.id,{version:1,status:'paused',requestKey:key()});f.m.update(f.bid,a.id,{version:1,status:'retired',requestKey:key()});f.m.update(f.bid,c.id,{version:1,status:'void',requestKey:key()});const snap=f.m.snapshot(f.bid);assert.equal(snap.records.length,3);assert.equal(snap.summary.assets,0);assert.equal(snap.summary.overdue,0);assert.equal(snap.summary.costs.forecast,0);assert.equal(f.m.history(f.bid,c.id).length,2);f.ws.close();});
