import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {compileSurfaces,prepareDisplayGroups,modelGroupVisible,appearanceSettings,displayPoint,viewStamp,inRings,distanceToSegment} from '../packages/viewer/surfaces.mjs';
import {placeEquipment,buildEquipmentGroups,equipmentMesh,meshBounds,compatibleLocation} from '../packages/equipment-demo/geometry.mjs';
const polygon=[[0,0],[10,0],[10,8],[0,8]],floor={id:0,key:'GF',y:0};
function plan(){return {floors:[floor],assets:[{id:'lobby',type:'space',title:'Entrance lobby',floor:0,pos:[2,4]}],shapes:[{f:0,kind:'slab',name:'Shared floor',p:polygon,holes:[],y:0,h:.2},{f:0,kind:'finish',name:'Lobby floor',p:polygon,holes:[],y:.2,h:.02}],segments:[{f:0,kind:'partition',a:[0,0],b:[0,8],w:.15,y:0,h:2.8}],objects:[]};}
const object=(style='alarm-panel',slot=0)=>({id:'demo-equipment-'+style,style,locationId:'lobby',slot});
function triangle(points=[[1,0,1],[2,0,1],[1,0,2]],kind='slab'){return {floor:0,kind,name:'Synthetic '+kind,basis:'drawing-derived',data:points.flatMap(p=>[...p,0,1,0,.5,.5,.5,0])};}
const state={floor:'all',mode:'exterior',furniture:true,plan:false},settings={exterior:'solid',opacity:.18,residences:true};
test('surface compilation is reused for the same read-only model',()=>{const p=plan(),before=JSON.stringify(p);assert.equal(compileSurfaces(p),compileSurfaces(p));assert.equal(JSON.stringify(p),before);});
test('display cleanup removes exact duplicates and degenerates without editing source geometry',()=>{const p=plan(),g=triangle(),duplicate=structuredClone(g),zero=triangle([[0,0,0],[0,0,0],[0,0,0]]),before=JSON.stringify([p,g]);const q=prepareDisplayGroups(p,[g,duplicate,zero]);assert.equal(q.audit.duplicates,1);assert.equal(q.audit.degenerate,1);assert.equal(q.audit.outputTriangles,1);assert.equal(JSON.stringify([p,g]),before);assert.notEqual(q.groups[0].vertices,g.data);});
test('different materials and building floors are not deleted as duplicates',()=>{const p=plan(),a=triangle(),b=triangle(),c=triangle();b.data[6]=.9;c.floor=1;assert.equal(prepareDisplayGroups(p,[a,b,c]).audit.outputTriangles,3);});
test('private interior selection hides only identified private triangles',()=>{const p=plan();p.assets.push({id:'flat',type:'space',title:'Apartment bedroom',floor:0,pos:[7,4]});p.assets[0].pos=[1,4];p.shapes[1].p=[[0,0],[2,0],[2,8],[0,8]];p.shapes.push({f:0,kind:'finish',name:'Apartment floor finish',p:[[2,0],[10,0],[10,8],[2,8]],y:.2,h:.02});const privateFloor=triangle([[6,.22,3],[8,.22,3],[6,.22,5]],'finish'),sharedFloor=triangle([[.5,.22,3],[1.5,.22,3],[.5,.22,5]],'finish'),q=prepareDisplayGroups(p,[privateFloor,sharedFloor]);assert.equal(q.groups.filter(g=>g.zone==='private').length,1);assert.equal(q.groups.filter(g=>modelGroupVisible(g,state,{...settings,residences:false})).length,1);assert.equal(q.audit.privateTriangles,1);});
test('residence toggle retains communal doors, structural slabs and stairs',()=>{for(const kind of ['door','slab','core-wall','stairs'])assert.ok(modelGroupVisible({kind,zone:'shared',floor:0},state,{...settings,residences:false}));});
test('exterior display is independent of private interiors and never moves vertices',()=>{const g=triangle(undefined,'facade'),before=JSON.stringify(g);assert.ok(modelGroupVisible(g,state,{...settings,exterior:'ghost'}));assert.equal(modelGroupVisible(g,state,{...settings,exterior:'hidden'}),false);assert.equal(JSON.stringify(g),before);});
test('selected floor hides upper floors and roof but retains full-height partition groups',()=>{const s={...state,floor:'0',mode:'cutaway',wallHeight:1.05};assert.ok(modelGroupVisible({kind:'partition',floor:0},s,settings));assert.equal(modelGroupVisible({kind:'partition',floor:1},s,settings),false);assert.equal(modelGroupVisible({kind:'roof',floor:0},s,settings),false);});
test('appearance messages validate enum, opacity and boolean values',()=>{assert.deepEqual(appearanceSettings(settings,{exterior:'remote-url',opacity:NaN,residences:'false'}),settings);assert.deepEqual(appearanceSettings(settings,{exterior:'ghost',opacity:.12,residences:false}),{exterior:'ghost',opacity:.12,residences:false});for(const n of [-1,0,1,Infinity])assert.equal(appearanceSettings(settings,{opacity:n}).opacity,.18);});
test('model markers keep x/height/z order and apply exactly one floor offset',()=>{const v={offset:()=>-7.65};assert.deepEqual(displayPoint(v,4,[-6,8.85,-13]),[-6,1.1999999999999993,-13]);assert.deepEqual(displayPoint({offset:()=>9.2},4,[2,7.65,5]),[2,16.85,5]);assert.equal(displayPoint(v,0,[1,2]),null);assert.equal(displayPoint(v,0,[1,NaN,3]),null);});
test('stable camera stamps ignore imperceptible motion but track floor and view changes',()=>{const v={width:800,height:600,explode:0,current:{theta:0,phi:1,radius:30,target:[0,0,0]}},a=viewStamp(v,state);v.current.theta=1e-8;assert.equal(viewStamp(v,state),a);assert.notEqual(viewStamp(v,{...state,floor:'0'}),a);});
test('a named equipment room is required, rather than the nearest arbitrary space',()=>{const a={type:'space',title:'Entrance lobby'};assert.equal(compatibleLocation('pump',a),false);assert.equal(compatibleLocation('electrical-board',a),false);assert.equal(compatibleLocation('alarm-panel',a),true);assert.equal(compatibleLocation('electrical-board',{...a,title:'Electrical cupboard'}),true);assert.equal(compatibleLocation('ev-charger',{...a,title:'Cycle store'}),false);assert.equal(compatibleLocation('pump',{...a,title:'Flat 1 plant room'}),false);});
test('missing bounds or unresolved installation rooms remain unplaced with reasons',()=>{const p=plan(),q=placeEquipment(p,[object()],null);assert.equal(q.placed.length,0);assert.match(q.reasons['demo-equipment-alarm-panel'],/bounded/);const noRoom=placeEquipment(p,[object('pump')],compileSurfaces(p));assert.equal(noRoom.placed.length,0);assert.match(noRoom.reasons['demo-equipment-pump'],/compatible/);});
test('wall devices have actual wall backing, full footprint clearance and face into their room',()=>{const p=plan(),q=placeEquipment(p,[object()],compileSurfaces(p)),placed=q.placed[0];assert.ok(placed);assert.ok(placed.backing);const g=buildEquipmentGroups(q.placed)[0],backDistance=distanceToSegment([placed.x,placed.z],placed.backing.a,placed.backing.b);assert.ok(backDistance<.5&&backDistance>.08);assert.ok(Math.sin(placed.rotation)>.9);assert.ok(g.bounds.lo[0]>.075);assert.ok(g.bounds.hi[1]>1.05);});
test('equipment placement preserves source and remains deterministic',()=>{const p=plan(),before=JSON.stringify(p),a=placeEquipment(p,[object(),object('call-point',1)],compileSurfaces(p)),b=placeEquipment(p,[object(),object('call-point',1)],compileSurfaces(p));assert.deepEqual(a,b);assert.equal(JSON.stringify(p),before);assert.ok(a.placed.length===2);});
test('door openings are not treated as suitable backing',()=>{const p=plan();p.segments.push({f:0,kind:'door',a:[0,0],b:[0,8],y:0,h:2.8,w:.15});assert.equal(placeEquipment(p,[object()],compileSurfaces(p)).placed.length,0);});
test('shaft openings do not accept floor-standing equipment',()=>{const p=plan();p.assets[0].title='Water plant room';p.shapes.forEach(s=>s.holes=[[[0,0],[10,0],[10,8],[0,8]]]);assert.equal(placeEquipment(p,[object('tank')],compileSurfaces(p)).placed.length,0);});
test('large symbols that cannot fit a small room are not forced through its walls',()=>{const p=plan();p.assets[0].title='Plant room';p.assets[0].pos=[.4,.4];for(const s of p.shapes)s.p=[[0,0],[.8,0],[.8,.8],[0,.8]];const q=placeEquipment(p,[object('tank')],compileSurfaces(p),{size:2});assert.equal(q.placed.length,0);});
test('cached mesh source cannot be modified by a caller',()=>{const a=equipmentMesh('alarm-panel'),b=equipmentMesh('alarm-panel');a[0]=999;assert.notEqual(a[0],b[0]);assert.deepEqual(equipmentMesh('alarm-panel'),b);});
test('all three device sizes retain full height when legacy cut controls change',()=>{for(const size of [1,1.5,2]){const p={...object(),floor:0,floorY:0,x:2,z:2,rotation:0,mount:'wall'};assert.deepEqual(buildEquipmentGroups([p],{size,capFloor:0,wallHeight:.2})[0].vertices,buildEquipmentGroups([p],{size,wallHeight:4})[0].vertices);}});

function rendererHarness({rejectShader=false}={}){
 const calls=[],events={},frames=[],p=plan(),g=triangle(),oldGroups=[g],uniforms={uVP:'uVP',uLightVP:'uLightVP',uOffset:'uOffset',uCap:'uCap'},gl=new Proxy({FRAGMENT_SHADER:2,SHADER_TYPE:3,COMPILE_STATUS:4,LINK_STATUS:5,getAttachedShaders:()=>[{type:1},{type:2}],getShaderParameter:(s,k)=>k===3?s.type:!rejectShader,getShaderSource:s=>s.type===2?'out vec4 outColor;void main(){outColor=vec4(result,1.);}':'vertex',createShader:type=>({type}),getProgramParameter:()=>true,getUniformLocation:(p,k)=>k,createProgram:()=>({}),createVertexArray:()=>({}),createBuffer:()=>({})},{get:(o,k)=>Object.hasOwn(o,k)?o[k]:(...args)=>calls.push([k,...args])});
 const viewer={gl,program:{},groups:oldGroups,uniforms:{shadow:uniforms},shadowProgram:{},current:{theta:0,phi:1,radius:20,target:[0,0,0]},camera:{theta:0,phi:1,radius:20,target:[0,0,0]},offset:()=>0,frame:()=>{},visible:()=>true,canvas:{width:200,height:120},width:200,height:120,explode:0,running:true,lastTime:0,lightVP:new Float32Array(16),night:0,onFrame:()=>{}};
 const pc={PLAN:p,viewer,state:{...state}},ctx=vm.createContext({Map,Set,WeakMap,JSON,Array,Object,Math,Number,Float32Array,Infinity,prepareDisplayGroups,compileSurfaces,createSurfacePicker:()=>()=>null,modelGroupVisible,exteriorKinds:new Set(['facade','window','roof']),appearanceSettings,viewStamp,AbortController,document:{hidden:false},parent:{postMessage:m=>calls.push(['message',m])},location:{origin:'https://fixture.test'},addEventListener:(n,fn)=>(events[n]||=[]).push(fn),requestAnimationFrame:fn=>frames.push(fn),pc});
 let source=readFileSync(new URL('../packages/viewer/scene.mjs',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replaceAll('export ','');vm.runInContext(source+';globalThis.scene=getScene(pc);',ctx);return {scene:ctx.scene,viewer,pc,calls,events,oldGroups,ctx};
}
test('native rendering disables vertex clamping and draws nothing repeatedly when stationary',()=>{const h=rendererHarness();h.viewer.frame(16);const first=h.scene.stats.draws;h.viewer.frame(32);h.viewer.frame(48);assert.equal(h.scene.stats.draws,first);assert.ok(h.calls.filter(c=>c[0]==='uniform1f'&&c[1]==='uCap').every(c=>c[2]===0));});
test('appearance-only toggles reuse buffers and update opacity without rebuilding geometry',()=>{const h=rendererHarness(),groups=h.viewer.groups,builds=h.scene.stats.geometryBuilds;h.scene.set({exterior:'ghost',opacity:.1});h.viewer.frame(16);assert.equal(h.viewer.groups,groups);assert.equal(h.scene.stats.geometryBuilds,builds);assert.equal(h.scene.alpha({kind:'facade'}),.1);assert.equal(h.scene.alpha({kind:'partition'}),1);});
test('failed transparency shader setup preserves original renderer ownership',()=>{assert.throws(()=>rendererHarness({rejectShader:true}),/shader compilation/);});
test('wrong-origin appearance commands cannot change the display',()=>{const h=rendererHarness(),handler=h.events.message[0],parent=vm.runInContext('parent',h.ctx);handler({source:parent,origin:'https://other.test',data:{source:'propertychecked-app',command:'modelAppearance',value:{residences:false}}});assert.equal(h.scene.settings.residences,true);});
test('appearance changes never set model condition or access permissions',()=>{const h=rendererHarness(),before=JSON.stringify(h.pc.PLAN);h.scene.set({residences:false,exterior:'hidden'});assert.equal(JSON.stringify(h.pc.PLAN),before);assert.equal(Object.hasOwn(h.scene.settings,'compliant'),false);});
test('scene disposal returns original arrays and rendering functions',()=>{const h=rendererHarness();assert.notEqual(h.viewer.groups,h.oldGroups);h.events.pagehide[0]();assert.equal(h.viewer.groups,h.oldGroups);});
test('one shared scene module replaces competing observers and interval marker controllers',()=>{const app=readFileSync(new URL('../apps/web/public/equipment-demo/app.js',import.meta.url),'utf8'),viewer=readFileSync(new URL('../packages/equipment-demo/viewer.js',import.meta.url),'utf8');assert.doesNotMatch(app,/new MutationObserver|ragObserver|setInterval\(\(\)=>/);assert.doesNotMatch(viewer,/propertychecked-rag-viewer/);assert.match(viewer,/geometryKey/);assert.match(app,/Model display/);assert.match(app,/Private residence interiors/);});
