import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createPreviewApp} from '../apps/api/preview-server.mjs';
import {createResearch,ResearchError} from '../apps/api/preview/research.mjs';
import {defaultSpec,previewModel} from '../packages/preview/model.mjs';
import {conceptZones,withConcept,conceptSVG,CONCEPT_NOTICE} from '../packages/preview/concept.mjs';
const offline={configured:()=>false},noMap={enabled:()=>false,lookup:async()=>({mapped:null})};
const png=()=>{const b=Buffer.alloc(32);Buffer.from([137,80,78,71,13,10,26,10]).copy(b);b.write('IHDR',12);b.writeUInt32BE(256,16);b.writeUInt32BE(256,20);return b;};
const image=()=>({id:'photo-source',title:'Synthetic exterior',description:'Synthetic test only',mime:'image/png',url:'https://example.org/building',imageUrl:'https://example.org/photo.png',bytes:png()});
const input=()=>({name:'Synthetic Court',postcode:'RH1 1RT',requestKey:randomUUID(),allowProcessing:true});
const found=()=>({images:[image()],notes:'A synthetic building',references:[],visualResearch:{loaded:1,used:0}});
async function harness(research=offline,maps=noMap){
  const dir=mkdtempSync(join(tmpdir(),'pc-photo-flow-'));let app,base,cookie,csrf;
  async function open(){app=createPreviewApp({dataDir:dir,assetsDir:join(dir,'none'),preview:{research:offline},photoFlow:{research,maps}});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+app.server.address().port;const r=await fetch(base+'/api/session');cookie=r.headers.get('set-cookie').split(';')[0];csrf=(await r.json()).csrf;}
  await open();
  const call=async(path,method='GET',body,headers={})=>{const r=await fetch(base+path,{method,headers:{cookie,Origin:base,'X-CSRF-Token':csrf,...(body?{'Content-Type':'application/json'}:{}),...headers},body:body?JSON.stringify(body):undefined});return {status:r.status,data:r.headers.get('content-type')?.includes('json')?await r.json():await r.arrayBuffer()};};
  const create=async(options={})=>{const r=await call('/api/photo-flow/jobs','POST',{...input(),...options});assert.equal(r.status,201);return r.data;};
  const action=async(j,a,data={})=>call('/api/photo-flow/jobs/'+j.id+'/'+a,'POST',{version:j.version,requestKey:randomUUID(),...data});
  const upload=async(j,kind='photo',bytes=png(),name='sample.png',extra={})=>{const r=await fetch(base+'/api/photo-flow/jobs/'+j.id+'/upload',{method:'POST',headers:{cookie,Origin:base,'X-CSRF-Token':csrf,'Content-Type':kind==='photo'?'image/png':'application/pdf','X-File-Kind':kind,'X-File-Name':encodeURIComponent(name),'X-File-Permission':'yes','X-Request-Key':randomUUID(),...extra},body:bytes});return {status:r.status,data:await r.json()};};
  return {get app(){return app;},get base(){return base;},call,create,action,upload,restart:async()=>{await app.close();await open();},close:async()=>{await app.close();rmSync(dir,{recursive:true,force:true});}};
}
async function settled(h,id){for(let i=0;i<200;i++){const r=(await h.call('/api/photo-flow/jobs/'+id)).data;if(!['searching','building'].includes(r.state))return r;await new Promise(r=>setTimeout(r,5));}throw new Error('Did not settle');}
test('no-key creation asks for a photo without generating or researching a model',async()=>{const h=await harness();try{const p=await h.create();assert.equal(p.state,'needs_photo');assert.equal(h.app.preview.list().length,0);assert.equal(p.aiConfigured,false);}finally{await h.close();}});
test('photo discovery stops for confirmation before map lookup and model creation',async()=>{let searches=0,maps=0;const h=await harness({configured:()=>true,discover:async()=>{searches++;return found();},run:async()=>assert.fail('Do not build before confirmation')},{lookup:async()=>{maps++;return {mapped:null};}});try{const p=await h.create(),r=await settled(h,p.id);assert.equal(r.state,'confirm');assert.equal(r.candidates.length,1);assert.equal(searches,1);assert.equal(maps,0);assert.equal(h.app.preview.list().length,0);assert.ok(r.candidates[0].imageUrl.startsWith('/api/photo-flow/assets/'));assert.equal(r.candidates[0].bytes,undefined);}finally{await h.close();}});
test('rejecting a photograph leads to upload and makes that candidate ineligible',async()=>{const h=await harness({configured:()=>true,discover:async()=>found()});try{const p=await h.create(),r=await settled(h,p.id),photoId=r.candidates[0].id;const no=await h.action(r,'reject');assert.equal(no.data.state,'needs_photo');assert.equal(no.data.candidates.length,0);assert.equal((await h.action(no.data,'build',{assetIds:[photoId],allowProcessing:true})).status,400);assert.equal(h.app.preview.list().length,0);}finally{await h.close();}});
test('same creation key or same building never triggers a second paid search',async()=>{let calls=0;const h=await harness({configured:()=>true,discover:async()=>{calls++;return found();}});try{const body=input(),a=await h.create(body);await settled(h,a.id);assert.equal((await h.create(body)).id,a.id);assert.equal((await h.create()).id,a.id);assert.equal(calls,1);assert.equal((await h.call('/api/photo-flow/jobs','POST',{...body,name:'Different'})).status,409);}finally{await h.close();}});
test('upload only stores documents and sources; it never invokes AI',async()=>{const h=await harness({configured:()=>true,discover:()=>assert.fail(),run:()=>assert.fail()});try{const p=await h.create({search:false}),r=await h.upload(p);assert.equal(r.status,201);assert.equal(r.data.uploads.length,1);assert.equal(h.app.workspace.documents(p.buildingId).length,1);assert.equal(h.app.preview.list().length,0);assert.equal(h.app.workspace.locations(p.buildingId).length,0);}finally{await h.close();}});
test('uploads require permission, valid images and a bounded known kind',async()=>{const h=await harness();try{const p=await h.create();assert.equal((await h.upload(p,'photo',png(),'a.png',{'X-File-Permission':'no'})).status,400);assert.equal((await h.upload(p,'photo',Buffer.from('<html>x</html>'),'image.png')).status,415);assert.equal((await h.upload(p,'unexpected')).status,400);assert.equal((await h.upload(p,'photo',png(),'../secret.png')).status,400);assert.equal(p.uploads.length,0);}finally{await h.close();}});
test('identical files and explicit upload retry keys are deduplicated',async()=>{const h=await harness();try{const p=await h.create(),k=randomUUID();const first=await h.upload(p,'photo',png(),'same.png',{'X-Request-Key':k});assert.equal(first.status,201);const again=await h.upload(p,'photo',png(),'same.png',{'X-Request-Key':k});assert.equal(again.data.uploads.length,1);assert.equal((await h.upload(p)).data.uploads.length,1);assert.equal((await h.upload(p,'photo',png(),'different.png',{'X-Request-Key':k})).status,409);}finally{await h.close();}});
test('real plans disable invented layouts but do not invent calibrated interiors',async()=>{const h=await harness();try{const p=await h.create();const r=await h.upload(p,'plan',Buffer.from('%PDF-1.4\nSynthetic test\n%%EOF'),'floor.pdf');assert.equal(r.status,201);assert.equal(r.data.hasPlans,true);assert.equal((await h.call('/api/photo-flow/buildings/'+p.buildingId)).data.hasPlans,true);assert.equal(h.app.workspace.locations(p.buildingId).length,0);assert.equal(h.app.preview.list().length,0);}finally{await h.close();}});
test('private photo reads and mutations keep session and CSRF guards',async()=>{const h=await harness();try{const p=await h.create(),r=await h.upload(p),id=r.data.uploads[0].id;assert.equal((await fetch(h.base+'/api/photo-flow/assets/'+id)).status,401);assert.equal((await h.call('/api/photo-flow/assets/'+id)).status,200);assert.equal((await h.call('/api/photo-flow/jobs/'+p.id+'/reject','POST',{version:p.version,requestKey:randomUUID()},{'X-CSRF-Token':''})).status,403);assert.equal((await fetch(h.base+'/api/photo-flow/buildings/'+p.buildingId)).status,401);}finally{await h.close();}});
test('build uses exact uploaded photo bytes without repeating discovery',async()=>{let calls=0;const h=await harness({configured:()=>true,discover:()=>assert.fail(),run:async({spec,prepared,usage})=>{calls++;assert.equal(prepared.images.length,1);assert.deepEqual(prepared.images[0].bytes,png());assert.equal(prepared.notes,'');spec.blocks[0].finish='render';spec.usedPhotoIds=[prepared.images[0].id];usage.responses=2;return {spec,basis:'ai-estimated',photos:prepared.photoMeta,references:[],message:'Photo estimate ready'};}});try{const p=await h.create({search:false}),r=(await h.upload(p)).data;const b=await h.action(r,'build',{assetIds:[r.uploads[0].id],allowProcessing:true});assert.equal(b.status,202);const done=await settled(h,p.id);assert.equal(done.state,'ready');const model=h.app.preview.get(done.previewId);assert.equal(model.spec.blocks[0].finish,'render');assert.equal(model.spec.usedPhotoIds.length,1);assert.equal(calls,1);assert.equal(h.app.workspace.locations(p.buildingId).length,0);}finally{await h.close();}});
test('a confirmed web photo is not silently replaced by a different candidate',async()=>{const h=await harness({configured:()=>true,discover:async()=>found(),run:async({spec,prepared})=>{assert.equal(prepared.images.length,1);spec.usedPhotoIds=[prepared.images[0].id];return {spec,basis:'ai-estimated',photos:prepared.photoMeta,references:[],message:'done'};}});try{const p=await h.create(),j=await settled(h,p.id),chosen=j.candidates[0].id;await h.action(j,'build',{assetIds:[chosen],allowProcessing:true});const r=await settled(h,p.id);assert.equal(r.state,'ready');assert.equal(h.app.preview.get(r.previewId).spec.usedPhotoIds[0],chosen);}finally{await h.close();}});
test('a photo from another building or a floor-plan file cannot become the facade input',async()=>{const h=await harness();try{const p=await h.create(),other=await h.create({name:'Other Court'}),o=(await h.upload(other)).data;assert.equal((await h.action(p,'build',{assetIds:[o.uploads[0].id],allowProcessing:true})).status,400);const plan=(await h.upload(p,'plan',Buffer.from('%PDF-1.4 x'),'plan.pdf')).data;assert.equal((await h.action(plan,'build',{assetIds:[plan.uploads[0].id],allowProcessing:true})).status,400);}finally{await h.close();}});
test('offline build completes honestly without claiming uploaded pixels were interpreted',async()=>{const h=await harness();try{const p=await h.create(),u=(await h.upload(p)).data;await h.action(u,'build',{assetIds:[u.uploads[0].id],allowProcessing:true});const r=await settled(h,p.id);assert.equal(r.state,'ready');assert.match(r.message,/not configured/);assert.equal(h.app.preview.get(r.previewId).spec.usedPhotoIds.length,0);}finally{await h.close();}});
test('an expired web reference cannot be served or submitted to a visual build',async()=>{const h=await harness({configured:()=>true,discover:async()=>found()});try{const p=await h.create(),j=await settled(h,p.id),id=j.candidates[0].id;h.app.workspace.db.prepare('UPDATE photo_flow_assets SET expires_at=0 WHERE id=?').run(id);assert.equal((await h.call('/api/photo-flow/assets/'+id)).status,410);assert.equal((await h.action(j,'build',{assetIds:[id],allowProcessing:true})).status,400);assert.equal((await h.call('/api/photo-flow/jobs/'+p.id)).data.state,'needs_photo');}finally{await h.close();}});
test('pause prevents a late search result appearing as a confirmed candidate',async()=>{let done;const h=await harness({configured:()=>true,discover:()=>new Promise(r=>done=r)});try{const p=await h.create();for(let i=0;i<50&&!done;i++)await new Promise(r=>setTimeout(r,3));const j=(await h.call('/api/photo-flow/jobs/'+p.id)).data;await h.action(j,'stop');done(found());await new Promise(r=>setTimeout(r,15));const after=(await h.call('/api/photo-flow/jobs/'+p.id)).data;assert.equal(after.state,'paused');assert.equal(after.candidates.length,0);}finally{done?.(found());await h.close();}});
test('restart retains uploaded media and confirmation state without paid replay',async()=>{let searches=0;const h=await harness({configured:()=>true,discover:async()=>{searches++;return found();}});try{const p=await h.create(),j=await settled(h,p.id);await h.upload(j);await h.restart();const r=(await h.call('/api/photo-flow/jobs/'+p.id)).data;assert.equal(r.state,'confirm');assert.equal(r.candidates.length,1);assert.equal(r.uploads.length,1);assert.equal(searches,1);}finally{await h.close();}});
test('manual changes made during a photo build are not overwritten',async()=>{let done;const h=await harness({configured:()=>true,run:async({spec})=>{await new Promise(r=>done=r);spec.blocks[0].floors=9;return {spec,basis:'ai-estimated',photos:[],references:[]};}});try{const p=await h.create({search:false}),u=(await h.upload(p)).data;await h.action(u,'build',{assetIds:[u.uploads[0].id],allowProcessing:true});for(let i=0;i<50&&!done;i++)await new Promise(r=>setTimeout(r,3));const j=h.app.photoFlow.get(p.id),saved=h.app.preview.get(j.previewId),spec=structuredClone(saved.spec);spec.blocks[0].floors=2;h.app.preview.edit(saved.id,{version:saved.version,spec});done();const r=await settled(h,p.id);assert.equal(r.state,'paused');assert.equal(h.app.preview.get(saved.id).spec.blocks[0].floors,2);}finally{done?.();await h.close();}});
test('one-page /build keeps inline uploads and specialist drawing tools remain available',async()=>{const h=await harness();try{const b=await fetch(h.base+'/build?building=test'),html=await b.text(),ui=await(await fetch(h.base+'/workspace-ui.js')).text();assert.equal(b.status,200);assert.match(html,/id="add-files"/);assert.match(ui,/id="photo-files"/);assert.match(ui,/id="plan-files"/);assert.match(ui,/Is this your building/);assert.match(html,/id="model-activity"/);assert.equal((await fetch(h.base+'/advanced-build')).status,200);assert.equal((await fetch(h.base+'/modules/preview/concept.mjs')).status,200);}finally{await h.close();}});
test('search-only adapter uses one response; resumed photo interpretation gets pixels in both passes',async()=>{let requests=[];const r=createResearch({key:()=> 'synthetic-key',photos:async()=>[image()],webPhotos:async()=>({images:[],attempts:[]}),fetcher:async(_u,options)=>{const q=JSON.parse(options.body);requests.push(q);return new Response(JSON.stringify({status:'completed',output:requests.length===1?[]:[{type:'message',content:[{type:'output_text',text:JSON.stringify(defaultSpec())}]}],usage:{input_tokens:1,output_tokens:1}}));}});const usage={responses:0,searchCalls:0,inputTokens:0,outputTokens:0},signal=new AbortController().signal,prepared=await r.discover({name:'A',postcode:'RH1 1RT',signal,usage});assert.equal(requests.length,1);assert.equal(prepared.images.length,1);await r.run({name:'A',postcode:'RH1 1RT',signal,usage,prepared,spec:defaultSpec(),onProgress:async()=>{}});assert.equal(requests.length,3);for(const q of requests.slice(1))assert.equal(q.input[0].content.filter(c=>c.type==='input_image').length,1);});
test('invented layout stays inside floor envelope, is labelled and does not mutate actual geometry',()=>{const m=previewModel(defaultSpec(),{floor:'0',cutaway:true}),before=JSON.stringify(m),zones=conceptZones(m),concept=withConcept(m);assert.ok(zones.length>2);assert.ok(zones.every(z=>z.fictional));assert.equal(JSON.stringify(m),before);assert.equal(concept.provenance.interior,CONCEPT_NOTICE);const area=zones.flatMap(z=>z.pieces).reduce((n,p)=>n+Math.abs(p.reduce((s,a,i)=>{const b=p[(i+1)%p.length];return s+a[0]*b[1]-b[0]*a[1];},0))/2,0);assert.ok(Math.abs(area-28*16)<.01);assert.match(conceptSVG(m),/not an actual floor plan/);assert.ok(concept.volumes.some(v=>v.provenance.height.source==='fictional'));});
test('failed new photo interpretation preserves previous source evidence and explicit error',async()=>{const h=await harness({configured:()=>true,run:async()=>{throw new ResearchError('HTTP_429','Temporary limit',{retryAfterSeconds:60});}});try{const p=await h.create({search:false}),u=(await h.upload(p)).data,prior=h.app.preview.create({name:p.name,postcode:p.postcode,requestKey:randomUUID(),allowProcessing:true},{deferResearch:true});const spec=defaultSpec();spec.usedPhotoIds=['old-photo'];h.app.preview.publishPrepared(prior.id,prior.version,{spec,meta:{photos:[{id:'old-photo',url:'https://example.org/old'}],references:[],basis:'ai-estimated'}});await h.action(u,'build',{assetIds:[u.uploads[0].id],allowProcessing:true});const j=await settled(h,p.id),after=h.app.preview.get(j.previewId);assert.equal(after.meta.photos[0].id,'old-photo');assert.equal(after.spec.usedPhotoIds[0],'old-photo');assert.match(after.spec.summary,/newly selected photos have not been interpreted/);assert.equal(after.stage,'fallback');assert.equal(after.meta.error.code,'HTTP_429');assert.equal((await h.action(j,'search',{allowProcessing:true})).status,429);}finally{await h.close();}});
test('high resolution plan image is retained byte-for-byte without photo resizing',async()=>{const h=await harness();try{const p=await h.create(),b=Buffer.concat([png(),Buffer.alloc(3*1024*1024)]),r=await h.upload(p,'plan',b,'large-plan.png');assert.equal(r.status,201);const d=h.app.workspace.document(r.data.uploads[0].documentId);assert.equal(d.size,b.length);assert.equal(r.data.hasPlans,true);assert.equal((await h.upload(p,'photo',b,'too-large.png')).status,415);}finally{await h.close();}});
