import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createPreviewApp } from '../apps/api/preview-server.mjs';
import { PreviewViewer } from '../packages/preview/viewer.mjs';
import { defaultSpec, previewModel } from '../packages/preview/model.mjs';
import { postcodeValue, propertyInput, modelBasis, stageSteps, statusCopy, retryRemaining, editBlock, matchesSaved, supportSummary, safeSource } from '../packages/preview/ux.mjs';

async function fixture(research={configured:()=>false,run:()=>{throw new Error('No live AI call is permitted in this test.');}}){
  const root=mkdtempSync(join(tmpdir(),'pc-ux-'));
  let app,base,cookie,csrf;
  async function open(){app=createPreviewApp({dataDir:root,assetsDir:join(root,'none'),preview:{research}});await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));base=`http://127.0.0.1:${app.server.address().port}`;const r=await fetch(base+'/api/session');cookie=r.headers.get('set-cookie').split(';')[0];csrf=(await r.json()).csrf;}
  await open();
  const call=async(path,method='GET',body,extra={})=>{const r=await fetch(base+path,{method,headers:{cookie,Origin:base,'Content-Type':'application/json','X-CSRF-Token':csrf,...extra},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json()};};
  const create=async()=>{const r=await call('/api/previews','POST',{name:'Synthetic House',postcode:'RH1 1RT',requestKey:randomUUID(),allowProcessing:true});assert.equal(r.status,201);return r.data;};
  return {call,create,get app(){return app;},get base(){return base;},restart:async()=>{await app.close();await open();},close:async()=>{await app.close();rmSync(root,{recursive:true,force:true});}};
}
for(const [input,expected] of [['rh1 1rt','RH1 1RT'],['RH11RT','RH1 1RT'],['  sw1a   1aa ','SW1A 1AA'],['gir0aa','GIR 0AA']])test('postcode formatting: '+input,()=>assert.equal(postcodeValue(input),expected));
test('two-field form reports errors without inventing a building match',()=>{const r=propertyInput('x','RH1');assert.ok(r.errors.name);assert.ok(r.errors.postcode);assert.equal(postcodeValue('RH1 1RT<script>'),null);assert.deepEqual(propertyInput(' Queensgate ','rh11rt').errors,{});});
test('unresolved and ambiguous estimates never acquire a verified label',()=>{assert.equal(modelBasis({spec:{matchBasis:'unresolved'},meta:{basis:'ai-estimated'}}),'Starting estimate');assert.equal(modelBasis({spec:{matchBasis:'ambiguous'}}),'Building match uncertain');assert.equal(modelBasis({basis:'user-adjusted-estimate'}),'Your adjusted estimate');});
test('local-only model does not falsely complete research progress',()=>assert.deepEqual(stageSteps({stage:'local',status:'ready'}).map(x=>x.state),['done','pending','pending','pending']));
test('in-flight and failed phases have accurate progress labels',()=>{assert.deepEqual(stageSteps({stage:'appearance',status:'refining'}).map(x=>x.state),['done','done','active','pending']);assert.deepEqual(stageSteps({stage:'fallback',status:'ready',meta:{events:[{stage:'research'},{stage:'appearance'}]}}).map(x=>x.state),['done','done','paused','pending']);});
test('research completion says ready while unresolved identity remains a concept',()=>{assert.ok(stageSteps({stage:'complete',status:'ready'}).every(s=>s.state==='done'));assert.match(statusCopy({stage:'complete',spec:{matchBasis:'unresolved'}}).detail,/starting concept/);});
test('error and pause copy retains the usable model instead of claiming data loss',()=>{for(const stage of ['fallback','budget','interrupted','stopped','local'])assert.ok(statusCopy({stage,status:'ready'}).title);assert.match(statusCopy({stage:'fallback'}).detail,/not been retried automatically/);});
test('Retry-After display is bounded at zero and supports absent or stale dates',()=>{const clock=Date.parse('2030-01-01T00:00:30Z');assert.equal(retryRemaining({meta:{error:{retryAfterSeconds:90}},updated_at:'2030-01-01T00:00:00Z'},clock),60);assert.equal(retryRemaining({},clock),0);assert.equal(retryRemaining({meta:{error:{retryAfterSeconds:1}},updated_at:'2030-01-01T00:00:00Z'},clock),0);});
test('local edits preserve other building sections and original geometry',()=>{const s=defaultSpec();s.blocks.push({...s.blocks[0],label:'Wing',x:40});const before=JSON.stringify(s),result=editBlock(s,1,{floors:'6',finish:'render',roof:'hip',balconies:true});assert.equal(result.blocks[0].floors,4);assert.equal(result.blocks[1].floors,6);assert.equal(result.blocks[1].roofHeight,1.5);assert.equal(JSON.stringify(s),before);});
test('invalid local controls are rejected rather than silently clamped',()=>{const s=defaultSpec();assert.throws(()=>editBlock(s,0,{floors:'2.5'}));assert.throws(()=>editBlock(s,0,{width:''}));assert.throws(()=>editBlock(s,9,{}));assert.throws(()=>editBlock(s,0,{finish:'unknown'}));});
test('saved search ignores postcode spaces and case',()=>{const items=[{name:'Synthetic House',postcode:'RH1 1RT'},{name:'Other',postcode:'SW1A 1AA'}];assert.equal(matchesSaved(items,'rh11rt').length,1);assert.equal(matchesSaved(items,'SYNTHETIC')[0].name,'Synthetic House');assert.equal(matchesSaved(items,'nothing').length,0);});
test('safe diagnostics omit keys, personal addresses, provider text and file paths',()=>{const text=supportSummary({id:'private-id',name:'Secret place',postcode:'RH1 1RT',stage:'fallback',meta:{error:{code:'HTTP_429',message:'sk-proj-secret C:/private'},key:'sk-secret'}},false);assert.match(text,/HTTP_429/);assert.doesNotMatch(text,/sk-|RH1|Secret|private-id|C:/);});
test('reference links do not admit script URLs or embedded credentials',()=>{assert.equal(safeSource('javascript:alert(1)'),null);assert.equal(safeSource('https://user:pass@example.org'),null);assert.equal(safeSource('https://example.org/source'),'https://example.org/source');});
test('configuration read requires authentication and never performs inference',async()=>{const f=await fixture();try{assert.equal((await fetch(f.base+'/api/previews/config')).status,401);const r=await f.call('/api/previews/config');assert.equal(r.status,200);assert.equal(r.data.researchConfigured,false);assert.equal(r.data.limits.responses,3);assert.deepEqual(Object.keys(r.data).sort(),['limits','researchConfigured','version']);}finally{await f.close();}});
test('save then undo restores geometry, source metadata and remains not surveyed',async()=>{const f=await fixture();try{const p=await f.create();const spec=editBlock(p.spec,0,{floors:7});const changed=await f.call('/api/previews/'+p.id,'PATCH',{version:p.version,spec});assert.equal(changed.status,200);assert.equal(changed.data.canUndo,true);const restored=await f.call('/api/previews/'+p.id+'/undo','POST',{version:changed.data.version});assert.equal(restored.status,200);assert.deepEqual(restored.data.spec,p.spec);assert.equal(restored.data.meta.basis,p.meta.basis);assert.equal(restored.data.canUndo,false);assert.match(restored.data.notice,/not surveyed/);assert.equal(f.app.workspace.buildings().length,1);}finally{await f.close();}});
test('undo persists after reopening the same local workspace',async()=>{const f=await fixture();try{const p=await f.create();const r=await f.call('/api/previews/'+p.id,'PATCH',{version:p.version,spec:editBlock(p.spec,0,{roof:'hip'})});await f.restart();const p2=(await f.call('/api/previews/'+p.id)).data;assert.equal(p2.canUndo,true);assert.equal(p2.version,r.data.version);assert.equal((await f.call('/api/previews/'+p.id+'/undo','POST',{version:p2.version})).status,200);}finally{await f.close();}});
test('stale edits and stale undo cannot replace a newer version',async()=>{const f=await fixture();try{const p=await f.create(),body={version:p.version,spec:editBlock(p.spec,0,{floors:8})};const r=await f.call('/api/previews/'+p.id,'PATCH',body);assert.equal((await f.call('/api/previews/'+p.id,'PATCH',body)).status,409);assert.equal((await f.call('/api/previews/'+p.id+'/undo','POST',{version:p.version})).status,409);assert.equal((await f.call('/api/previews/'+p.id+'/undo','POST',{version:r.data.version})).status,200);assert.equal((await f.call('/api/previews/'+p.id+'/undo','POST',{version:r.data.version})).status,409);}finally{await f.close();}});
test('undo without an edit is a controlled conflict',async()=>{const f=await fixture();try{const p=await f.create();assert.equal((await f.call('/api/previews/'+p.id+'/undo','POST',{version:p.version})).status,409);}finally{await f.close();}});
test('invalid input leaves version, model and undo state untouched',async()=>{const f=await fixture();try{const p=await f.create(),spec=structuredClone(p.spec);spec.blocks[0].floors=-1;const r=await f.call('/api/previews/'+p.id,'PATCH',{version:p.version,spec});assert.equal(r.status,422);const after=(await f.call('/api/previews/'+p.id)).data;assert.equal(after.version,p.version);assert.deepEqual(after.spec,p.spec);assert.equal(after.canUndo,false);}finally{await f.close();}});
test('undo rolls back only the last manual edit',async()=>{const f=await fixture();try{const p=await f.create(),first=(await f.call('/api/previews/'+p.id,'PATCH',{version:p.version,spec:editBlock(p.spec,0,{floors:7})})).data,second=(await f.call('/api/previews/'+p.id,'PATCH',{version:first.version,spec:editBlock(first.spec,0,{floors:8})})).data;const r=await f.call('/api/previews/'+p.id+'/undo','POST',{version:second.version});assert.equal(r.data.spec.blocks[0].floors,7);}finally{await f.close();}});
test('undo requires CSRF even with an authenticated session',async()=>{const f=await fixture();try{const p=await f.create();assert.equal((await f.call('/api/previews/'+p.id+'/undo','POST',{version:p.version},{'X-CSRF-Token':''})).status,403);}finally{await f.close();}});
test('gallery returns small safe summaries without full source documents',async()=>{const f=await fixture();try{await f.create();const r=await f.call('/api/previews');assert.equal(r.data[0].storeys,4);assert.equal(r.data[0].blocks,1);assert.equal(r.data[0].basis,'generic-starting-estimate');assert.equal(r.data[0].spec,undefined);assert.equal(r.data[0].meta,undefined);}finally{await f.close();}});
test('late AI output cannot overwrite a manual edit or its undo snapshot',async()=>{let release;const research={configured:()=>true,run:async({spec})=>{await new Promise(r=>release=r);const next=structuredClone(spec);next.blocks[0].floors=20;return {spec:next,basis:'ai-estimated',references:[],photos:[],message:'mock complete'};}};const f=await fixture(research);try{const p=await f.create();for(let i=0;!release&&i<20;i++)await new Promise(r=>setTimeout(r,5));assert.ok(release);const fresh=(await f.call('/api/previews/'+p.id)).data,edited=(await f.call('/api/previews/'+p.id,'PATCH',{version:fresh.version,spec:editBlock(fresh.spec,0,{floors:6})})).data;release();await new Promise(r=>setTimeout(r,20));const after=(await f.call('/api/previews/'+p.id)).data;assert.equal(after.spec.blocks[0].floors,6);assert.equal(after.canUndo,true);assert.equal(after.version,edited.version);assert.equal((await f.call('/api/previews/'+p.id+'/undo','POST',{version:after.version})).data.spec.blocks[0].floors,4);}finally{release?.();await f.close();}});
test('new static UX modules and accessible controls are served without a CDN',async()=>{const f=await fixture();try{for(const path of ['/start','/instant.js','/instant.css','/modules/preview/ux.mjs']){const r=await fetch(f.base+path);assert.equal(r.status,200);}const html=await(await fetch(f.base+'/start')).text();assert.match(html,/role="tablist"/);assert.match(html,/id="connection-banner"/);assert.match(html,/id="undo"/);assert.doesNotMatch(html,/src="https?:/);}finally{await f.close();}});
test('responsive camera fit widens its distance on portrait viewports',()=>{
  const v={host:{getBoundingClientRect:()=>({width:900,height:500})},model:{extent:{minX:0,maxX:28,minY:0,maxY:16}},high:25,low:0,baseTarget:[14,12,-8],invalidate(){}};
  PreviewViewer.prototype.fit.call(v);const wide=v.radius;
  v.host.getBoundingClientRect=()=>({width:320,height:500});PreviewViewer.prototype.fit.call(v);
  assert.ok(v.radius>wide);assert.deepEqual(v.target,v.baseTarget);assert.notEqual(v.target,v.baseTarget);
});
test('isolated upper floor is centred on that floor rather than ground level',()=>{
  const spec=defaultSpec();spec.blocks[0].floors=8;
  const model=previewModel(spec,{floor:'7'}),v={pack(){}};
  PreviewViewer.prototype.build.call(v,model);
  assert.equal(v.low,21);assert.ok(v.baseTarget[1]>21);assert.ok(v.baseTarget[1]<v.high);
});
