import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile, mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApp } from '../apps/api/server.mjs';
import { trackingItems,trackingSections,communalLocation,trackingSuggestions,searchTracking,trackingPreset,trackingActions,issueMarkers } from '../packages/management/tracking-library.mjs';
import { compileSurfaces,createSurfacePicker,rayTriangle,pointInRing,partitionFloor,resolveSurfaceHit } from '../packages/viewer/surfaces.mjs';
const area={id:'test-lobby',floor_key:'GF',type:'space',title:'Communal lobby',source:'TEST',basis:'drawing-derived'};
const triangle=(y,kind='slab',floor=0)=>({floor,kind,data:[0,y,0,0,1,0,1,1,1,0,4,y,0,0,1,0,1,1,1,0,0,y,4,0,1,0,1,1,1,0]});
function planFixture(){return {floors:[{id:0,key:'GF',y:0},{id:1,key:'FF',y:3}],shapes:[{f:0,kind:'slab',p:[[0,0],[8,0],[8,6],[0,6]],holes:[],y:0,h:.15},{f:0,kind:'finish',p:[[0,0],[2,0],[2,6],[0,6]],holes:[],y:.15,h:.02}],segments:[{f:0,kind:'partition',a:[2,0],b:[2,6],w:.16,h:2.6,y:0},{f:0,kind:'door',a:[4,0],b:[5,0],w:.06,h:2.1,y:0}],objects:[],assets:[{id:'test-corridor',floor:0,type:'space',title:'Common corridor',source:'TEST',basis:'drawing-derived',pos:[1,3]},{id:'test-door',floor:0,type:'door',title:'Entrance door',source:'TEST',basis:'estimated',pos:[4.5,0]},{id:'test-room',floor:0,type:'space',title:'Plant room',source:'TEST',basis:'drawing-derived',pos:[5,3]}]};}

test('catalogue contains 171 distinct practical record prompts across 19 existing responsibilities',()=>{assert.equal(trackingItems.length,171);assert.equal(trackingSections.length,19);assert.equal(new Set(trackingItems.map(i=>i.id)).size,171);for(const i of trackingItems){assert.ok(i.scope.length>35);assert.ok(i.label&&i.category&&i.tags.length);assert.equal(i.dueDate,undefined);assert.equal(i.interval,undefined);}});
test('tracking search returns matching topics without dropping uncommon facilities',()=>{for(const word of ['pump','roof','asbestos','cleaning','lift','contract','drainage','evacuation','cycle','intercom','balcony','waste'])assert.ok(searchTracking(word).length>0,word);assert.ok(searchTracking('repair','water').every(i=>i.category==='water'));});
test('communal directory uses explicit shared-space descriptions, not private flats or voids',()=>{for(const title of ['Entrance lobby','Main corridor','Cycle store','Plant room','Residential bins','Community use'])assert.equal(communalLocation({...area,title}),true,title);for(const title of ['Living / kitchen','Private terrace','Lower-wing apartment','Bedroom'])assert.equal(communalLocation({...area,title}),false,title);assert.equal(communalLocation({...area,type:'void'}),false);assert.equal(communalLocation({...area,type:'stairs',title:'Main stair'}),true);assert.equal(communalLocation(null),false);});
test('suggestions prioritise communal area registration and are not automatically installed records',()=>{const s=trackingSuggestions(area);assert.equal(s[0].id,'cleaning-communal-area');assert.ok(s.every(i=>!i.status&&!i.evidenceIds));});
test('asset prompt remains unconfirmed and does not fabricate equipment evidence',()=>{const i=trackingItems.find(i=>i.category==='water'),p=trackingPreset(i,'asset',area);assert.equal(p.status,'unconfirmed');assert.equal(p.data.basis,'unconfirmed');assert.equal(p.locationId,area.id);assert.equal(p.evidenceIds,undefined);});
test('communal area record retains the original location ID and drawing basis',()=>{const i=trackingItems.find(i=>i.id==='cleaning-communal-area'),p=trackingPreset(i,'asset',area);assert.equal(p.data.equipment,'Communal area');assert.equal(p.data.basis,'drawing_derived');assert.equal(p.locationId,'test-lobby');assert.match(p.notes,/Catalogue prompt only/);});
test('new check starts paused and never invents a statutory interval or first due date',()=>{const p=trackingPreset(trackingItems[0],'schedule',area);assert.equal(p.status,'paused');assert.equal(p.data.intervalUnit,'none');assert.equal(p.dueDate,undefined);assert.match(p.data.basisReference,/Set applicability/);});
test('invalid catalogue actions and custom forged item IDs are rejected',()=>{assert.throws(()=>trackingPreset({id:'unknown'},'asset',area));assert.throws(()=>trackingPreset(trackingItems[0],'delete',area));});
test('issue-only markers remove reference, ordinary, unconfirmed and future-only blobs',()=>{const entries=[['problem',true,true],['plain',true,false],['due-soon',true,false],['unconfirmed',true,false],['old',false,true]].map(([id,active,attention])=>({record:{id},location:{id:'x'},flags:{active,attention}}));const h=entries.map(e=>({id:e.record.id,recordIds:[e.record.id],reference:false,count:1}));h.push({id:'drawing',reference:true,count:0,recordIds:[]});const markers=issueMarkers({matches:entries,highlights:h});assert.deepEqual(markers.map(m=>m.id),['problem']);});
test('mixed locations count only active issues and do not mutate saved record lists',()=>{const v={matches:[{record:{id:'a'},location:{id:'x'},flags:{active:true,attention:true}},{record:{id:'b'},location:{id:'x'},flags:{active:true,attention:false}}],highlights:[{id:'x',recordIds:['a','b'],reference:false,count:2}]};const before=JSON.stringify(v);assert.equal(issueMarkers(v)[0].count,1);assert.deepEqual(issueMarkers(v)[0].recordIds,['a']);assert.equal(JSON.stringify(v),before);});
test('an empty register produces no dots',()=>assert.deepEqual(issueMarkers({matches:[],highlights:[]}),[]));
test('ray hits the actual nearest visible surface rather than a point through the building',()=>{const groups=[triangle(0),triangle(2,'roof')],pick=createSurfacePicker(groups),ray={origin:[1,5,1],dir:[0,-1,0]};assert.equal(pick(ray).group.kind,'roof');assert.equal(pick(ray,{visible:g=>g.kind!=='roof'}).point[1],0);});
test('picking follows isolated and exploded floor transforms',()=>{const g=triangle(3,'slab',1),pick=createSurfacePicker([g]),ray={origin:[1,10,1],dir:[0,-1,0]};assert.equal(pick(ray,{offset:()=>-3}).point[1],0);assert.equal(pick(ray,{offset:()=>2.3}).point[1],5.3);});
test('picking respects wall-height clipping and does not mutate triangle coordinates',()=>{const g=triangle(3),before=JSON.stringify(g),pick=createSurfacePicker([g]);assert.equal(pick({origin:[1,5,1],dir:[0,-1,0]},{cap:()=>1.1}).point[1],1.1);assert.equal(JSON.stringify(g),before);});
test('parallel, behind-camera and missed triangles return no hit',()=>{const a=[0,0,0],b=[4,0,0],c=[0,0,4];assert.equal(rayTriangle({origin:[1,2,1],dir:[1,0,0]},a,b,c),null);assert.equal(rayTriangle({origin:[1,2,1],dir:[0,1,0]},a,b,c),null);assert.equal(rayTriangle({origin:[8,2,8],dir:[0,-1,0]},a,b,c),null);});
test('known corridor highlight follows the source-model polygon, not a marker circle',()=>{const p=planFixture(),s=compileSurfaces(p).byId.get('test-corridor');assert.equal(s.polygons[0][0],p.shapes[1].p);assert.equal(s.contains([1,4]),true);assert.equal(s.contains([3,4]),false);assert.match(s.boundaryBasis,/Existing model/);});
test('door highlighting follows the existing oriented segment and retains estimates',()=>{const s=compileSurfaces(planFixture()).byId.get('test-door');assert.equal(s.basis,'estimated');assert.ok(s.segment);assert.equal(s.contains([4.5,0]),true);assert.equal(s.contains([6,0]),false);});
test('floor partition regions are bounded by model walls and outer plates',()=>{const p=planFixture(),g=partitionFloor(p,p.floors[0]),left=g.seed([1,3]),right=g.seed([5,3]);assert.notEqual(left,right);assert.equal(g.contains(left,[5,3]),false);assert.equal(g.contains(left,[-1,3]),false);});
test('floor-zone holes remain holes in hover geometry',()=>{const p=planFixture();p.shapes[1].holes=[[[.5,2],[1.5,2],[1.5,3],[.5,3]]];p.assets[0].pos=[1,4];const s=compileSurfaces(p).byId.get('test-corridor');assert.equal(s.contains([1,2.5]),false);assert.equal(s.contains([1,4]),true);});
test('unresolved shared regions retain separate tracking IDs without invented walls',()=>{const p=planFixture();p.assets.push({...p.assets[2],id:'second-name',pos:[6,3],title:'Cycle store'});const r=compileSurfaces(p),a=r.byId.get('test-room'),b=r.byId.get('second-name');assert.ok(a.sharedIds.includes(b.id));assert.match(a.boundaryBasis,/not resolved/);assert.equal(a.contains([6,3]),true);});
test('compile and repeated picking cannot modify original model geometry or provenance',()=>{const p=planFixture(),before=JSON.stringify(p);compileSurfaces(p);compileSurfaces(p);assert.equal(JSON.stringify(p),before);});
test('a foreground facade does not select a hidden corridor',()=>{const p=planFixture(),r=compileSurfaces(p);assert.equal(resolveSurfaceHit(r,{group:{floor:0,kind:'facade'},point:[1,1,3]}),null);assert.equal(resolveSurfaceHit(r,{group:{floor:0,kind:'finish'},point:[1,.17,3]}).id,'test-corridor');});
test('hover module retains messaging checks and uses only trusted private-model coordinates',async()=>{const s=await readFile(new URL('../packages/viewer/interaction.js',import.meta.url),'utf8');assert.match(s,/e\.source!==parent/);assert.match(s,/e\.origin!==parentOrigin/);assert.match(s,/known\.has\(e\.data\.value\)/);assert.doesNotMatch(s,/fetch\(|XMLHttpRequest|innerHTML|localStorage|eval\(/);assert.match(s,/originalFrame\?\.call/);assert.match(s,/originalPick/);});
test('tracking UI submits nothing on hover, preserves form dirty handling and escapes names',async()=>{const s=await readFile(new URL('../apps/web/public/management/quiet.js',import.meta.url),'utf8');assert.doesNotMatch(s,/fetch\(|XMLHttpRequest|api\(/);assert.match(s,/escapeHtml/);assert.match(s,/record-dialog/);assert.match(s,/new Event\('input'/);assert.match(s,/surface-choice/);});
test('static interaction routes are explicit and the viewer remains session protected',async()=>{const s=await readFile(new URL('../apps/api/server.mjs',import.meta.url),'utf8');assert.match(s,/Object\.hasOwn\(interactionFiles,path\)/);assert.match(s,/\/viewer-interaction.js/);assert.match(s,/\/modules\/viewer\/surfaces.mjs/);assert.match(s,/requireSession/);});
test('new routine work has an issue marker without mislabelling it overdue',()=>{const e={record:{id:'work-new',kind:'work'},location:{id:'x'},flags:{active:true,attention:false,tone:'recorded'}},v={matches:[e],highlights:[{id:'x',reference:false,recordIds:['work-new'],tone:'recorded',colour:'#366eae'}]};const h=issueMarkers(v)[0];assert.equal(h.tone,'work');assert.equal(h.count,1);assert.doesNotMatch(h.label,/overdue/i);});
test('financial, responsibility and resident topics prepare appropriate typed records',()=>{for(const [category,expected] of [['residents','resident'],['safety','responsibility'],['finance','cost']]){const i=trackingItems.find(i=>i.category===category),a=trackingActions(i)[0];assert.equal(a.kind,expected);assert.equal(trackingPreset(i,a.kind,null).kind,expected);}const i=trackingItems.find(i=>i.label==='Service contract');assert.equal(trackingActions(i)[0].kind,'contract');});
test('new static hover modules serve with correct MIME and private viewer still requires a session',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'pc-quiet-http-'));const assets=join(dir,'private','marketfield');await mkdir(assets,{recursive:true});
 await writeFile(join(assets,'manifest.json'),JSON.stringify({meta:{},floors:[],assets:[],sources:[]}));
 await writeFile(join(assets,'viewer.html'),'<!doctype html><html><head><title>TEST ONLY</title></head><body>synthetic viewer</body></html>');
 const app=createApp({dataDir:join(dir,'data'),assetsDir:join(dir,'private')});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;
 try {
  for(const path of ['/management-quiet.js','/management-quiet.css','/modules/management/tracking-library.mjs','/modules/viewer/surfaces.mjs','/viewer-interaction.js','/viewer-interaction.css']){
   const r=await fetch(base+path);assert.equal(r.status,200,path);assert.equal(r.headers.get('content-type'),path.endsWith('.css')?'text/css; charset=utf-8':'text/javascript; charset=utf-8');assert.ok((await r.text()).length>100);
  }
  assert.equal((await fetch(base+'/api/models/marketfield/viewer')).status,401);
  const session=await fetch(base+'/api/session'),cookie=session.headers.get('set-cookie').split(';')[0];
  const v=await fetch(base+'/api/models/marketfield/viewer?embed=1',{headers:{Cookie:cookie}});assert.equal(v.status,200);assert.match(v.headers.get('content-security-policy'),/connect-src 'none'/);const html=await v.text();assert.match(html,/viewer-interaction.js/);assert.match(html,/viewer-bridge.js/);
  assert.equal((await fetch(base+'/modules/viewer/missing.mjs')).status,404);
  assert.equal(app.workspace.tasks('marketfield').length,0);
 }finally{await app.close();await rm(dir,{recursive:true,force:true});}
});
