import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const code=await readFile(new URL('../packages/viewer/bridge.js',import.meta.url),'utf8');
class Classes {constructor(){this.values=new Set();}add(...v){v.forEach(x=>this.values.add(x));}remove(...v){v.forEach(x=>this.values.delete(x));}contains(v){return this.values.has(v);}toggle(v,on){if(on===undefined)on=!this.contains(v);on?this.add(v):this.remove(v);return on;}}
class El {constructor(){this.children=[];this.classList=new Classes();this.events={};this.attributes={};this.style={setProperty:(k,v)=>{this.style[k]=v;}};this.hidden=false;}append(...e){this.children.push(...e);}replaceChildren(){this.children=[];}setAttribute(k,v){this.attributes[k]=v;}addEventListener(t,fn){this.events[t]=fn;}remove(){}click(){this.events.click?.({stopPropagation(){}});}}
function harness(){const events={},timers=[],messages=[],root=new El(),canvas=new El();canvas.parentElement=root;let frames=0;const projects=[];
 const pc={ready:true,assets:[{id:'a',title:'Location A',floor:0,type:'door',pos:[100,1.1,100]},{id:'b',title:'Location B',floor:1,type:'riser',pos:[200,4.1,200]}],PLAN:{floors:[{id:0,y:0},{id:1,y:3}]},state:{floor:'all',mode:'exterior',selected:null,exploded:false},viewer:{canvas,width:500,height:500,explode:0,onFrame(){frames++;},project(p){projects.push(p);return {x:p[0],y:p[2],z:0};},setCamera(){}},setFloor(f){this.state.floor=f;},setMode(){},select(id){this.state.selected=id;},toggleExplode(){},togglePlan(){}};
 const document={documentElement:root,activeElement:null,createElement:()=>new El(),getElementById:id=>root.children.find(e=>e.id===id)||null};
 const parent={postMessage:(m,target)=>messages.push({m,target})},context={location:{search:'?embed=1',origin:'http://localhost:3000'},document,parent,PC:pc,URLSearchParams,innerWidth:1000,innerHeight:800,requestAnimationFrame:fn=>fn(),setInterval:fn=>{timers.push(fn);return 1;},clearInterval(){},setTimeout:()=>1,clearTimeout(){},addEventListener:(t,fn)=>{(events[t]||=[]).push(fn);}};context.window=context;
 vm.runInNewContext(code,context);
 const send=(value,extra={})=>{const event={source:parent,origin:context.location.origin,data:{source:'propertychecked-app',command:'highlights',value},...extra};for(const fn of events.message||[])fn(event);};
 return {pc,document,root,send,messages,projects,timers,events,context,parent,get overlay(){return root.children.find(e=>e.id==='pc-management-highlights');},get frames(){return frames;}};
}
const payload=(items=[{id:'a',colour:'#c34247',symbol:'!',count:2,title:'Two records',label:'Action'}])=>({enabled:true,labels:true,dim:true,selected:'',items});
test('bridge ignores foreign origins and non-parent message senders',()=>{const h=harness();h.send(payload(),{origin:'https://other.example'});h.send(payload(),{source:{}});assert.equal(h.overlay,undefined);h.send(payload());assert.equal(h.overlay.children.length,1);});
test('bridge resolves asset positions internally; arbitrary coordinates and unknown IDs cannot add a pin',()=>{const h=harness();h.send(payload([{id:'fake',colour:'#ff0000',count:1,pos:[1,2,3]},{id:'a',colour:'#ff0000',count:1,pos:[999,999,999]}]));h.pc.viewer.onFrame(100);assert.equal(h.overlay.children.length,1);assert.deepEqual([...h.projects[0]],[100,1.1,100]);});
test('bad colours, oversized lists, duplicate IDs and invalid counts are rejected',()=>{const h=harness();h.send(payload([{id:'a',colour:'url(javascript:x)',count:1},{id:'a',colour:'#123456',count:1},{id:'a',colour:'#123456',count:1},{id:'b',colour:'#123456',count:-1}]));assert.equal(h.overlay.children.length,1);h.send(payload(Array(1001).fill({id:'b',colour:'#123456',count:1})));assert.equal(h.overlay.children.length,1);});
test('titles are text, not HTML, and clicking sends only a known location to exact origin',()=>{const h=harness();h.send(payload([{id:'a',colour:'#123456',count:1,title:'<img onerror=bad()>',label:'Saved record'}]));const pin=h.overlay.children[0];assert.equal(pin.children[1].textContent,'<img onerror=bad()>');pin.click();const sent=h.messages.at(-1);assert.equal(sent.target,'http://localhost:3000');assert.equal(sent.m.type,'highlight-select');assert.equal(sent.m.locationId,'a');assert.equal(Object.keys(sent.m).length,3);});
test('frame integration preserves original drawing callback and original geometry',()=>{const h=harness(),before=JSON.stringify(h.pc.assets);h.send(payload());h.pc.viewer.onFrame(100);h.pc.viewer.onFrame(200);assert.equal(h.frames,2);assert.equal(JSON.stringify(h.pc.assets),before);assert.ok(h.overlay.children[0].style.transform.includes('translate(100px,100px)'));});
test('exploded and isolated floor positions use existing floor elevations',()=>{const h=harness();h.send(payload([{id:'b',colour:'#123456',count:1}]));h.pc.viewer.explode=1;h.pc.viewer.onFrame(100);assert.ok(Math.abs(h.projects.at(-1)[1]-6.4)<1e-9);h.pc.state.floor='1';h.pc.viewer.onFrame(200);assert.ok(Math.abs(h.projects.at(-1)[1]-1.1)<1e-9);h.pc.state.floor='0';h.pc.viewer.onFrame(300);assert.equal(h.overlay.children[0].hidden,true);});
test('overlapping markers declutter; selected marker remains, all records still exist',()=>{const h=harness();h.pc.assets[1].pos=[100,4.1,100];h.send({...payload([{id:'a',colour:'#123456',count:1},{id:'b',colour:'#123456',count:2}]),selected:'b'});h.pc.viewer.onFrame(100);assert.equal(h.overlay.children.filter(e=>!e.hidden).length,1);assert.equal(h.overlay.children[1].hidden,false);assert.equal(h.messages.at(-1).m.hidden,1);});
test('reference styling and highlight-off restore normal model visibility without deletion',()=>{const h=harness();h.send(payload([{id:'a',colour:'#657982',count:0,reference:true}]));assert.match(h.overlay.children[0].className,/pc-reference/);assert.equal(h.overlay.children[0].children[0].textContent,'D');assert.equal(h.root.classList.contains('pc-layer-dim'),true);h.send({...payload(),enabled:false});assert.equal(h.root.classList.contains('pc-layer-dim'),false);assert.equal(h.root.classList.contains('pc-layer-active'),false);assert.equal(h.overlay.hidden,true);assert.equal(h.pc.assets.length,2);});
test('clear selection never moves or changes source geometry',()=>{const h=harness();h.pc.state.selected='a';h.send(null,{data:{source:'propertychecked-app',command:'clearSelection'}});assert.equal(h.pc.state.selected,null);assert.equal(h.pc.state.floor,'all');});
test('ready handshake advertises capability without claiming saved assets',()=>{const h=harness();h.timers[0]();const ready=h.messages.find(s=>s.m.type==='ready');assert.equal(ready.m.capabilities[0],'record-highlights');assert.equal(h.overlay,undefined);});
