/** The structured appearance contract is shared with the actual geometry renderer. */
export const ARCHITECTURE_PROMPT = `
Return architecture version 1, not only a coloured massing box. Inspect the supplied photo PIXELS and encode the recognisable visible features in this schema:
- facades: at most 24 elevation/vertical-range profiles. Each has block (0-based), edge (local index from envelope, or -1 for all edges), start/end along that edge (0..1), firstFloor/lastFloor (inclusive 0..24). Ground floor can have a different profile from upper floors. Split an elevation into start/end regions to represent brick piers, render panels, glazed bays or blank walls. Specific edges override edge -1. Do not assign an edge as a measured compass direction. Photo-to-edge alignment remains a best guess; explain uncertainty in note. Do not stamp distinctive front details on every unseen elevation.
- Colours: six-digit #RRGGBB wallColour, frameColour, glassColour, accentColour; use muted representative observed colours, not prose. surface plain/brick/horizontal/vertical drives procedural material detail. WindowStyle casement/sash/picture/ribbon/bay/none; set none on observed solid regions. windowWidth 0.4..5m, windowHeight 0.4..4m, sillHeight 0.1..2.5m, spacing 1..10m, panesX/panesY integer 1..4. Estimate window aspect ratio, frame colour and mullion divisions from the actual photograph. These dimensions are approximate, not photogrammetric measurements.
- Balconies: none/projecting/juliet, balconyEvery integer 1..6, balconyDepth 0.2..2.5m, railing metal/glass. band none/sill/floor. Set none when not supported; use projecting only for visible projecting slabs, juliet for railings close to openings. Never add balconies merely to look detailed.
- entrances: at most 8, block and explicit edge index, position 0.05..0.95 along edge, width 0.7..6m, height 1.8..4m, canopyDepth 0..3m, doubleDoor boolean, colour #RRGGBB. Use a visible entrance, not invented safety/fire doors. Leave the array empty when no entrance is identifiable.
- roofColour #RRGGBB; parapetHeight 0..1.5m. roofFeatures at most 12: chimney/rooflight/dormer/plant, block index, u/v 0.02..0.98 within the block's LOCAL width/depth, width/depth 0.3..6m, height 0.1..4m, colour. Only include recognisable observed roof features; unknown roofs do not acquire decorative chimneys, plant or rooflights. Features outside the footprint or over a courtyard will be omitted. Roof shape remains simplified.
- Every profile/entrance/roof feature has sourcePhotoIds (maximum 4) referencing only supplied images genuinely used. Missing/unseen details have []. Add a note for each facade separating visible appearance from uncertain positioning and proportions. Never invent source IDs. Architecture metadata is an estimate, never verification or material specification.
Keep unknown details simple. With no useful photograph, return an empty facades/entrances/roofFeatures array and a conservative roof colour/parapet; do not claim photo analysis. The renderer can supply visibly labelled generic detail. Do not derive interiors from EXTERIOR photos. Fictional demonstration interiors are created separately and cannot enter this output as discovered rooms or escape routes.
`;
